### ISSUE TITLE
Add settings to hide previous email text in compose form

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#104]
Received by email from a beta-tester

**Comment by clochix** [comment]
Do you mean allowing to toggle visibility of previous message text, or removing it before replying ?

**Comment by aenario** [comment]
The user comes from Gmail, so its probably the same he wants : 

default behaviour is to hide the content of the previous message
(~ blockquote display:none}

There is a toggle to display it if one wants to reply below/inside the previous message

**Comment by clochix** [comment]
I'm not in favor of adding one more setting, so I only added “…” near reply header that allow to show / hide text of original message.
Text is shown by default. Maybe could we link this to the "compose on top" setting : hiding message when user chose to compose on top, showing it otherwise ?

**Comment by aenario** [comment]
"we link this to the "compose on top" setting : hiding message when user chose to compose on top, showing it otherwise"

+1

**Comment by frankrousseau** [comment]
Looks good.
