### ISSUE TITLE
Gmail Security message bug

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#108]
"assurez-vous d'être connecté avec le compte [object Object] "

**Comment by frankrousseau** [comment]
What is the way to reproduce it?

**Comment by aenario** [comment]
Try to setup a new account with a gmail address.
The message should be "assurez-vous d'être connecté avec le compte xxxxx@gmail.com" instead of "[Object object]

**Comment by aenario** [comment]
(inside the gmail security warning)

**Comment by frankrousseau** [comment]
Ok it works fine. Thx to both of you!
