### ISSUE TITLE
Report connection error

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#111]
If the user credentials stop working (changed password, disable access for less secure app on gmail, ect ...), an error is not displayed to the user.

**Comment by clochix** [comment]
There's a linked problem : due to the use of `asyncSeries`, when there's a problem refreshing one account, it stop the refresh process and other accounts are not updated. Should I open another issue for this ?

**Comment by clochix** [comment]
@poupotte I think we could close this one and open another issue for the above bug: when there's a problem refreshing an account (server temporally unavailable), refresh won't update next accounts.

**Comment by poupotte** [comment]
Yes, sure. I added issue #154 .
