### ISSUE TITLE
Allow to filter messages on flags

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#115]
Some work has already be done, allowing to filter messages to only display unread or flagged ones. To cleanup the UI, it's currently hidden under a hidden pref. What should we do?

**Comment by poupotte** [comment]
@clochix , actually, we can filter messages on unread, attachment and important flags. Do you want other filters or it's enough for you ?

**Comment by clochix** [comment]
This issue was only meant to not forget filter code that was hidden. It has now been removed and replaced by a new implementation, so we can close this ☺
