### ISSUE TITLE
Have one slider by mailbox in default menu.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#120]
When I display all folders in my first mailbox, I have to slide all folders to access to my next mailbox. It should be nice to have my other mailbox after the slider.

![menu](https://cloud.githubusercontent.com/assets/2659119/5897928/3a9d4800-a54a-11e4-840d-cdb4efd59f66.png)

In picture, I can't access to my 'Perso' mailbox without slide all folders.

**Comment by clochix** [comment]
I currently have 4 accounts defined. Making them fixed so they are always displayed wouldn't let much vertical space to display mailboxes.
I personally use the 3 panes view, menu items are smaller and I can see all my accounts.

**Comment by poupotte** [comment]
With new design, in my mind, this issue is no more relevant.
