### ISSUE TITLE
Navigate to previous / next message is broken when displaying conversations

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#137]
When displaying conversations, the navigation is broken, it navigates to previous / next conversation, not previous / next messages inside conversation.

**Comment by poupotte** [comment]
It doesn't work well. Indeed, on some conversations, I block on it. 

Moreover, I'm not sure about what behavior navigation should have. @clochix, @frankrousseau, @jsilvestre, @aenario, what do you think ? It's better to navigate to previous/next conversation (Gmail-like) or to navigate to previous/next message (Thunderbird-like in conversation mode).
Personnaly, I prefer navigate to previous/next conversation but it's just my opinion.

**Comment by aenario** [comment]
+1 on Gmail-like.

**Comment by clochix** [comment]
For the record, when you don't display conversations in message list, you navigate inside messages from the message list. when you fold conversations in message list, you navigate into messages inside the conversation. I did this because of #146 : @goofy-bz has hard time navigating inside a huge conversation.
