### ISSUE TITLE
Add tooltips for action button

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#138]

**Comment by poupotte** [comment]
Mmmm... it works on the first message, but if I open older messages in a conversation, tooltips don't work for its.

**Comment by poupotte** [comment]
Moreover, when I click on a button after tootip apparition, tooltip doesn't disappear,  I have to move my mouse.
![tooltip](https://cloud.githubusercontent.com/assets/2659119/7131463/f8c2a27c-e27f-11e4-99b9-b28fc3c5dff6.png)

**Comment by jsilvestre** [comment]
About the tooltip that doesn't fadeout, I opened an issue on aria-tips: https://github.com/m4dz/aria-tips/issues/4.

**Comment by frankrousseau** [comment]
I face the same bugs.

**Comment by jsilvestre** [comment]
I managed to reproduce the bug that on other messages, tooltips are not shown. I'm just scratching a bit my head around the matter. Also pushed fixes to aria-tips, I will work a bit more on it in order to make it smoother.

**Comment by jsilvestre** [comment]
@poupotte I did more improvements, there is still the bug you mentioned because I don't manage to reproduce it with aria-tips alone...What should we do with this issue?

**Comment by poupotte** [comment]
Issue in aria-tips is sufficient for the issue but it lacks tooltips for some buttons, so this issue must stay opened.

**Comment by poupotte** [comment]
Thanks @jsilvestre
