### ISSUE TITLE
In mail edition, display kown contacts as label. 

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#140]

**Comment by poupotte** [comment]
Contacts labels are nice but when we write to enter a new contact, labels switch.

**Comment by poupotte** [comment]
Moreover, I think, we can put all contacts (known and unknown) as label to have a similarity between all (maybe, you can use adress mail as label).

**Comment by clochix** [comment]
Fixed label switch, using label for all contacts is still a WIP, sorry ☹

**Comment by poupotte** [comment]
I add an specific issue for contacts label (#198). 

For labels switching, when i write labels seem still switch (but quickly and keeping the order)

**Comment by poupotte** [comment]
Nice, thanks @clochix.
