### ISSUE TITLE
Allow to add signature for emails

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#141]

**Comment by frankrousseau** [comment]
I think I can handle that one. Can we add it to the sprint?

**Comment by poupotte** [comment]
Ok.

**Comment by clochix** [comment]
I think it would be great to allow a different signature for each account. So, maybe adding this to the account config screen.

**Comment by frankrousseau** [comment]
Yes I would like to add this to the config screen.

**Comment by poupotte** [comment]
If I haven't signature defined, it displays 'undefined' instead of nothing:  
![signature](https://cloud.githubusercontent.com/assets/2659119/7365615/37099960-ed92-11e4-8e5e-70998625292e.png)

**Comment by poupotte** [comment]
I can't change my signature. Buttons in setting account page aren't available : 

![account](https://cloud.githubusercontent.com/assets/2659119/7365704/0ce3c1fa-ed93-11e4-8087-2880f6077692.png)

**Comment by aenario** [comment]
fix in https://github.com/aenario/cozy-emails/commit/780c4e9e73c615912ac50e023c945bd74563f691
It is a problem with React keys.

**Comment by frankrousseau** [comment]
Ok. It should be fixed by https://github.com/cozy/cozy-emails/pull/392

**Comment by frankrousseau** [comment]
@aenario your fix is included in a huge PR. That's why I did it in a separated one.

**Comment by aenario** [comment]
np, #392 was merged and #391 was rebased to remove this part

**Comment by poupotte** [comment]
It works well. Thanks @frankrousseau .

Just a small things, in plain text, I have two `---` before my signature but this issue seems related to #360.

**Comment by frankrousseau** [comment]
The extra hyphens will be removed in the next build. Thank you @poupotte for the review
