### ISSUE TITLE
Doesn't display contact information for me.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#143]

**Comment by clochix** [comment]
First step in e66461d (only in message list), is it enough ?

**Comment by frankrousseau** [comment]
On the right side of the screen, when a conversation is displayed, there is list of message represented by the list of person who are involved in this conversation. Each line should only display the sender of the message instead of the whole list each time.

**Comment by m4dz** [comment]
I take it as it rely on the view improvements suggested in the message / conversation rendering :wink:.
