### ISSUE TITLE
Contact pop up is opened too quickly and doesn't disappear.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#145]
From https://forum.cozy.io/t/experience-utilisateur-avec-cozymail-en-vue-conversation/240, contact displaying should be improved by open it only on user click.

**Comment by clochix** [comment]
I updated the rule so contact popup only opens when hovering the contact for more than 5 seconds, or on click.

**Comment by poupotte** [comment]
Thanks @clochix . It's better like that. @goofy-bz, it is ok for you ?

It will be available in **version 0.6.8**

**Comment by poupotte** [comment]
I close this issue. I'll reopen it if someone is not ok.
