### ISSUE TITLE
Improve conversation displaying

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#146]
From https://forum.cozy.io/t/experience-utilisateur-avec-cozymail-en-vue-conversation/240, @goofy-bz describes example where conversation displaying should be improved.

**Comment by clochix** [comment]
@goofy-bz some fixes will be available in *version 0.6.8* that improve navigation inside conversations: you can use the arrows inside message toolbar, or keyboard shortcuts: up and down arrows, or, for Vi lovers, j and k. It's only a workaround, but I hope it could improve your user experience.

**Comment by poupotte** [comment]
After discussion we have decided to keep navigate to previous/next conversation (instead of message). Later, we want to add other keyboard shortcuts to navigate in previous/next message inside a conversation. That's why I close this issue and open an other about navigation inside a conversation (#166) .
