### ISSUE TITLE
Error displaying quotation in messages

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#147]
See message sent by @jsilvestre « Re: [team] fichiers et activités toile » on 2015-02-02 10:56

The quoting of Frank's answer is wrong, in HTML and in Text mode.

**Comment by jsilvestre** [comment]
For the record, it has been sent from Roundcube.

**Comment by clochix** [comment]
Roundcube ? Why are you still using it ? :p 
I checked message source and it's well formatted, something goes wrong with the regular expressions I use to add some color to the message.

**Comment by jsilvestre** [comment]
Because I can't see which messages are read or unread in our app...

**Comment by clochix** [comment]
Could you open an issue with a screenshot ?

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
