### ISSUE TITLE
Improve spinner

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#149]
I suggest to use cozy-mobile spinner   https://github.com/poupotte/cozy-files-mobile/blob/master/www-src/app/assets/img/spinner.svg for email application.

**Comment by frankrousseau** [comment]
See PR: https://github.com/cozy/cozy-emails/pull/258

**Comment by frankrousseau** [comment]
Done.

**Comment by poupotte** [comment]
Thanks @frankrousseau
