### ISSUE TITLE
While creating a gmail account Hide/Show advanced parameters are reversed

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#150]
![example](https://cloud.githubusercontent.com/assets/1580287/6023158/aec7a544-abc2-11e4-9aac-fe1bc7b38620.jpg)

**Comment by clochix** [comment]
Labels were reversed in english locale

**Comment by poupotte** [comment]
It works well. Thanks @clochix .
@aenario , it is ok for you ?

It wiil be available in **version 0.6.8**

**Comment by aenario** [comment]
Yes
