### ISSUE TITLE
Actions on selected messages in conversation view

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#153]
When I view message list in conversation mode, action on selected messages should apply to the whole conversation. Currently they only apply to the first message.

**Comment by clochix** [comment]
Also, allow to undelete a conversation, see #164

**Comment by clochix** [comment]
Delete and undelete of conversation should now work better.

**Comment by poupotte** [comment]
Mmmmm it seems work but I've some strange behaviors.

I suppose, application deletes message one by one. 
Thus, if I received mails between two messages of a conversation, when I delete this conversation, I see my conversation move in my message list. 

I think, this problem will be solved with #132.  For now, maybe, delete messages from older solves this behavior.

**Comment by frankrousseau** [comment]
Sometimes it crashes my application too. I remove the 5 first selected messages. Then it gets stuck.

**Comment by poupotte** [comment]
It works for me. Thanks @clochix .
