### ISSUE TITLE
Improve font

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#159]
Personnaly, I prefer font used before #148, I think we have find a better font. What do you think about that ?

**Comment by clochix** [comment]
@frankrousseau in #148, I added Signika-Bold for bold, to fix the problem with Chrome on MacOS, and replaced Signika-Light by Signika-Regular for normal text. But I agree with @poupotte and preferred Signika-Light. “it was better before”. What do you think ?

**Comment by frankrousseau** [comment]
I think you should not use Signika. We changed to Source Sans specially for this kind of problem. So use source-sans-pro font. You can find it in the other apps. You can find the bold version on the Adobe dedicated website?
