### ISSUE TITLE
Message deletion doesn't work

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#160]
Message deletion seems broken. When I click to delete a message, I don't received error (interface or console) but my message isn't removed.

Moreover, confirmation pop up is quite weird :
![remove](https://cloud.githubusercontent.com/assets/2659119/6078055/6717cb4a-adf5-11e4-942c-11ef08b07c51.png)

**Comment by poupotte** [comment]
Pop up problem is fixed for me. However, I still can't remove my mail. @aenario, @frankrousseau can you test with your cozy to know if it is specific to me.

**Comment by frankrousseau** [comment]
Yes, message deletion is broken too.

**Comment by poupotte** [comment]
Actually none deletion works on conversation mode but it works in other mode. Maybe, this issue is a duplication of #77.

**Comment by poupotte** [comment]
It works weel with #181

**Comment by poupotte** [comment]
Thanks @clochix
