### ISSUE TITLE
Undelete messages is broken

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#164]

**Comment by poupotte** [comment]
It doesn't seem work for me. When I delete a message (in conversation without message confirmation). If a enter Ctrl-Z, I receive a message : 'Undo not available'. None error in my console.
Moreover, I haven't the pop up to undelete, Is it desired ?

**Comment by poupotte** [comment]
Actually, I tested with trash in messages list. 
With trash in message, it works.
Thus, this issue works and my problem is related to #153 .
Thanks @clochix .
