### ISSUE TITLE
Improve contacts displaying in mail edition

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#167]
If I add lots of contacts when I compose an email, new contacts should be displayed in a new line.

**Comment by clochix** [comment]
Should I remove the button on the left than trigger autocomplete ? I would prefer keeping it, but don't know what to do when the input field grows.

**Comment by poupotte** [comment]
After discussion with @clochix, we decided to separate button and input to keep button (without resize) when we add a line for contacts.

**Comment by poupotte** [comment]
It works well for label and input. Thanks @clochix .

**Comment by frankrousseau** [comment]
Don't push it in published until the new version is created.
