### ISSUE TITLE
Removing "add contact tooltip" in the message list

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-emails#173]
When I click on a message in the message list, it sometimes open the contact tooltip, and it's annoying.

**Comment by poupotte** [comment]
Thanks for your report.

Actually, to open the contact tooltip, you have two choices : 
   * Click on contact name (in mail or message list)
   * Stay 5 seconds on the contact name (mail or message list)

Maybe, to avoid your inconvenience, we could display contact tooltip only on mail (not in message list). Thus, contact tooltip should be less anoying but to add a contact, you should open mail.

What do you think @clochix ? Personnaly, I'm ok with @jsilvestre. I think the contact tooltip is enough just in mail.

**Comment by jsilvestre** [comment]
We talked about it yesterday, and I suggested him what you just suggested. @clochix told me he had a fix on the way and needed an issue.

**Comment by poupotte** [comment]
Thanks @clochix, contact tooltip is well removed from messages list. However, now, to add contact we have to unfold headers in mail. In other words, we can add contact in picture 2 but not in picture 1. In my mind, we shouldn't be able to add contact in message list but we should in mail (contact unfold or not).

**Picture 1:**
![contact_1](https://cloud.githubusercontent.com/assets/2659119/6169709/abfd4e04-b2cf-11e4-867d-88e6945a6a9a.png)

**Picture 2:**
![contact_2](https://cloud.githubusercontent.com/assets/2659119/6169718/b95d8af0-b2cf-11e4-9be7-06e3e1585f34.png)

**Comment by poupotte** [comment]
It works well. Thanks @clochix . @jsilvestre , it's ok for you ?

**Comment by jsilvestre** [comment]
Perfect !
