### ISSUE TITLE
Infinite scrolling is broken

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-emails#175]
* When I try to load more messages by scrolling down, I see a spinner. 
* Then I have "load more message" button, but nothing more.
* If click the button, more messages are loaded.
* Then the infinite scrolling works again.

**Comment by clochix** [comment]
I think this only happens when the "load more" button is visible before you scroll, I have a fix.

**Comment by poupotte** [comment]
It seems work, @jsilvestre, it is ok for you ?

**Comment by frankrousseau** [comment]
It works for me.

**Comment by jsilvestre** [comment]
It works for me too!
