### ISSUE TITLE
Keyboard shortcuts help

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#180]
With new version, the panel for keyboard shortcuts is weird with Firefox (ok with Chrome) : 

![shortcuts_helping](https://cloud.githubusercontent.com/assets/2659119/6169443/cb5c5daa-b2cd-11e4-8582-399db100bc0e.png)

**Comment by clochix** [comment]
I'm unable to reproduce, could you give me your advanced font setting so I try to reproduce and fix in every browsers ?

**Comment by poupotte** [comment]
I use Firefox 35.0.1 on Ubuntu 14.04 without specific font settings.

**Comment by clochix** [comment]
I had hard time reproducing it, so I blindly tried something, tell me if it works better.

**Comment by frankrousseau** [comment]
It works for me.

**Comment by poupotte** [comment]
Nice, it works. Good job @clochix :)
