### ISSUE TITLE
Remove progress bars during refresh

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-emails#183]
@frankrousseau and I discussed the fact that the orange progress bars are misleading for the users during the refresh operation.

I am going to remove them, and use spinner.svg to discreetly mark something is running in the background.

Let me know if you disagree / want something else.

**Comment by poupotte** [comment]
Thanks @jsilvestre  for this suggestion, I'm ok  with you.

**Comment by poupotte** [comment]
It works well, thanks @jsilvestre . It will be even better with new spinner :) !

**Comment by jsilvestre** [comment]
I was not sure to add the new spinner in place of the existing button, that's why I didn't add it...

**Comment by frankrousseau** [comment]
What did you do finally? From what I read, there is more progress bar and you finally drop the idea to use a spinner.

**Comment by jsilvestre** [comment]
I removed the progress bar during refresh, and messed up my commit description (noticed it when it was merged). I didn't add the spinner, I used .fa-spin on the refresh icon instead, that looked more logical to me.

**Comment by frankrousseau** [comment]
Ok. It makes things clearer. About the spinner, we want to use the same spinner in every place. That why we shouldn't use the Font awesome spinner.

**Comment by frankrousseau** [comment]
The progress bar is still displayed on subfolders.

**Comment by jsilvestre** [comment]
I don't use the font awesome spinner, .fa-spin makes spin whatever icon there is. It's the refresh icon that spins. That seemed more logical in the current UI, thus I agree that it's not coherent with other Cozy applications. Do you want me to the Cozy spinner anyway?

About the progressbar for subfolder, I will have a look.

**Comment by frankrousseau** [comment]
Yes, I think the Cozy spinner is better.

**Comment by jsilvestre** [comment]
Let's do it then.
