### ISSUE TITLE
"Selected email" indicator never disappears

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-emails#184]
The blue background in the message list, indicating the message is selected, is always visible even if the message is not open. I always wonder wether it's a bug or a wanted behaviour.

**Comment by clochix** [comment]
It's a wanted behavior, for keyboard navigation. So you can navigate with keyboard shortcuts, opening and closing message at will.

**Comment by jsilvestre** [comment]
Thank you, I understand better. I'll look for a way to improve my bad feeling about this if other people complain.
