### ISSUE TITLE
Unable to type a contact name with a space in it

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#185]
Every time I hit the “space” key, the space char is suppressed.

**Comment by poupotte** [comment]
I can hit a space in contact name but if I add a character after, it removes autocompletion. Is it wanted ?

**Comment by clochix** [comment]
The autocompletion filters on the exact string you entered. Are there results matching what you enter ? I'm able to type “Jean de la” and the autocompletion suggest “Jean de la Fontaine”

**Comment by poupotte** [comment]
For me, if I enter 'Jean' or 'Jean ', it suggests 'Jean de la Fonctaine' but if I enter 'Jean d' it removes autocompletion suggestion.

**Comment by clochix** [comment]
Funny one, works for "jean " and "jean de" but not "jean d". Anyway, fixed it.

**Comment by poupotte** [comment]
Thanks @clochix, now, I can easily send mail to 'jean de la fontaine' ;).
