### ISSUE TITLE
Messages should have same size selected or not

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#190]
When I select a message, every messages take more space (due to checkbox selection).
Thus, if I select a message far on my list, message down, this behaviour is weird.

In my mind, messages should have same size selected or not.

**Comment by clochix** [comment]
It may depend on some browser font setting, because on my computer I only noticed a very small move, even when selecting a message deep in the list. I hope this fix will work for you.

**Comment by poupotte** [comment]
There is no more move but now contact icon are too large : 

![list](https://cloud.githubusercontent.com/assets/2659119/6266336/8d4f6d52-b838-11e4-81f0-1879b923b2ba.png)

**Comment by clochix** [comment]
Avatars should be fixed now

**Comment by poupotte** [comment]
Nice, it works well. Thans @clochix.
