### ISSUE TITLE
Message selection : action button should be always visible.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#191]
In my mind, in message selection, button (move, delete, ...) should be always visible.
Indeed, currently, if I select a message far on my list, I have to scroll to the top to click on button.

**Comment by clochix** [comment]
I played a bit with this yesterday, but am not very satisfied by the result. We may revert this and try to find a better way to handle this.

**Comment by poupotte** [comment]
Mmmm... personnally I like it except two things : 
  * '...' are displayed with buttons (for contacts or body message)
  * button background is smaller than messages list width. Thus, message color are displayed on right.

![button_list](https://cloud.githubusercontent.com/assets/2659119/6266667/c07d7f12-b83c-11e4-8015-5c00821db3d5.png)

**Comment by clochix** [comment]
That's why I'm not comfortable with my hack. Sometime the menu is to small, sometime it's to wide and hover the scrollbar. Depends on the layout and probably the navigator. So it may work but it's not very strong. We should find a better way to do this.
Nevertheless, the last commit fixes the bug with "…".

**Comment by poupotte** [comment]
Ok, it works for me. I keep this issue opened as reminder.

**Comment by clochix** [comment]
It's broken on small screens ☹

**Comment by poupotte** [comment]
Yes, it's broken on small screens and I find a problem with error displaying (see image).  Maybe, we have to revert this change and keep it for later.

![error](https://cloud.githubusercontent.com/assets/2659119/6328963/b0aa5082-bb6c-11e4-85ff-516673644c34.png)

**Comment by frankrousseau** [comment]
+1 for revert

**Comment by poupotte** [comment]
With new design, this issue is fixed. Thanks @m4dz .
