### ISSUE TITLE
Selected message indicator moves during refresh

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-emails#194]
When I refresh my account, if there are new emails, they are added on top of the previous one (logical). But the selected message indicator (blue background) stays on the email it was before the refresh, and doesn't stay on the first message of the list.

I don't know what should be the exact behaviour, though.

**Comment by clochix** [comment]
Imagine you're reading a message when a new one comes. I think you don't want the new message to be automatically opened. So not updating current selected message when new ones come seems legit. IMHO.

**Comment by jsilvestre** [comment]
You are absolutely right if the user is reading a message. My remark was for the case no message is open.

**Comment by poupotte** [comment]
It works well. Thanks @jsilvestre  :)
