### ISSUE TITLE
Mailbox refresh

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#195]
Automatic mailbox refresh doesn't seem work. 

Two examples : 
   * If you don't connect you to your cozy during one day, when you come back, you haven't new mail (even if you wait). Email should be refresh when application is restarted.
   * If you force email to don't stop, mails don't seem automatically refresh. 

In my mind, we have to refresh automatically mails when app starts and every x minutes.

**Comment by clochix** [comment]
This is a first step: we refresh the favorites mailboxes of every account every 5 minutes.
Listening for new messages in mailboxes is a little bit harder, so I opened #209 to improve the refresh.

Also, please be aware that there's two types of refreshes:
 - full refresh: scan every message of every mailbox of every account. It may take quite a long time for "big" mailboxes, so it's only performed on application start and when user explicitly ask a refresh;
 - partial refresh: this one, only fetches latest messages from mailboxes the user marked as favorite.

@aenario please correct me if I'm wrong.

**Comment by poupotte** [comment]
Refresh box seems ok, thanks @clochix .
