### ISSUE TITLE
Use label for all contacts in mail edition

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#198]

**Comment by poupotte** [comment]
Thanks @clochix , I've no more problems with contacts labels.

**Comment by frankrousseau** [comment]
For information, it works well on my Cozy but the performances are poo, it takes like 20s to display the label.

**Comment by poupotte** [comment]
Actually, it seems create label when you wait several seconds or when you enter a ',' . @clochix, Am I wrong ?

**Comment by clochix** [comment]
By bad, the contact should become a tag when you enter ',' or leave the field (we should probably add an helper).
