### ISSUE TITLE
Improve newline when send mail

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#200]
In mail mail reading, newlines are displayed as new paragraph.

Example : 
1 - **Mail edition**
![paragraphe_1](https://cloud.githubusercontent.com/assets/2659119/6329825/09cc475e-bb74-11e4-8cdc-14ec51731fc1.png)

2 - **Mail reading**
![paragraphe_2](https://cloud.githubusercontent.com/assets/2659119/6329834/15451fb6-bb74-11e4-81f2-fd2c261635a8.png)

**Comment by poupotte** [comment]
Currently mail is bad displayed in others clients (like Thunderbird or Gmail). Thus, problem isn't in mail displaying but when we send mail.

**Comment by clochix** [comment]
HTML formatting depends on the rich text editor we use. Some people are not comfortable with `medium-editor` and we have discussed replacing it by a more classic one like CKEditor. Should we keep medium-editor or choose another one ?

**Comment by frankrousseau** [comment]
We keep medium editor.

**Comment by poupotte** [comment]
Lines are well displayed in Cozy and Gmail but there is still an issue with Thunderbird (I havn't tested on other clients) : 

![paragraphe_3](https://cloud.githubusercontent.com/assets/2659119/6465458/906bab44-c1c1-11e4-8e5c-16678b9893cb.png)

**Comment by frankrousseau** [comment]
For information, it works well on my thunderbird.

**Comment by poupotte** [comment]
Ok, I retried with my Thunderbird and it works.

The first time I sent the mail an my personnal box, then I did a copy/paste of content on a new mail to send on my professional box. Thus, maybe, the problem comes from the copy/paste. 
I close this issue and if I can reproduce my first issue, I'll open an new issue about copy/paste (or an other thing).

**Comment by clochix** [comment]
Yes, the issue arise when pasting.
I hacked medium editor so every time you hit enter, it add a `br` instead of embedding current text inside a paragraph tag.
But when you paste content, it's not cleaned.

**Comment by frankrousseau** [comment]
Yes copy paste with line breaks doesn't work well.
