### ISSUE TITLE
Remove settings panel

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#201]
From @frankrousseau, to facilitate our application, we have to temporary remove settings panel.

I propose to keep as default options :  
**Settings**:  
* Display layout: vertical
* Message list style: normal
* Display conversation: true
* Rich message editor: true
* Rely on top of message: false
* Display message in HTML: true
* Display images inside messages: false
* Confirm before deleting a message: true
* Display message preview: true
* Notification: false 

**Add-on** : 
* Attachments gallery
* Keyboard shortcuts
* Medium editor
* Sample
* Contacts VCards
 
It's just a proposition, don't hesitate to discuss in this issue if you consider that an option isn't the main used by users.

**Comment by clochix** [comment]
What shall we do for current users that have set settings different from this default ones ?

**Comment by poupotte** [comment]
We force default settings (in hard coding) :/ . 
It's rought but if we don't do that, it is useless to remove settings pannel.

**Comment by frankrousseau** [comment]
For the layout I suggest the vertical one with small labels in the menu.

**Comment by clochix** [comment]
@frankrousseau for now you have to choose between Three panes layout, which has small boxes labels, and Vertical layout, with big labels.

**Comment by frankrousseau** [comment]
I like the the Three panels layout, which has small boxes labels. It lacks of a big button to check your inbox but the overall is clearer. If you prefer the Vertical one, it's ok too.

**Comment by frankrousseau** [comment]
You should implement that early in the sprint. It will help to focus.

**Comment by poupotte** [comment]
In new version, settings pannel is well removed. Thanks @clochix.
