### ISSUE TITLE
Empty message for some event invites

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#211]
When sending an invite from Mozilla Thunderbird Lightning in "Outlook compatibility mode", the message contains no body nor attachment.
We should display a default text to the user instead of an empty message.

**Comment by poupotte** [comment]
To test this issue, I sent me an empty mail. 

When I read it on application, I have an empty message instead of  a default text : 
![empty_mail](https://cloud.githubusercontent.com/assets/2659119/6662456/2353aade-cbbc-11e4-9018-7f9ea5bb02bb.png)

**Comment by poupotte** [comment]
After discussion with @clochix , my test was inappropriate.
Indeed, if someone send an empty message, it ordinary to dislay nothing in content message.

I'll test this specific use case.

**Comment by poupotte** [comment]
Thanks @clochix , it works for me.
