### ISSUE TITLE
Nothing happens when refreshing if login/pass is incorrect

### ISSUE THREAD

**Issue by sylzys** [cozy/cozy-emails#215]
If your login, or more often your password becomes incorrect after a successful configuration, nothing seems to happen when you try to synchronize the mailbox.
-> A click on the refresh icons launches nothing visually (the spinner is not showing) and no error message is displayed.

If you come back to the mailbox config, the errors on address / password are well highlighted.

After you change your password for the good one, come back to the email view and try to synchronize again, everything goes smooth, i.e the spinner is spinning on click and your mails are fetched.

**Comment by poupotte** [comment]
It doesn't work on my cozy :( . 
I changed my Gmail account password. When I try to refresh my mailbox, I have none error displayed. 

I haven't error on my javascript console.

**Comment by jsilvestre** [comment]
I didn't build my PR, sorry...

**Comment by poupotte** [comment]
It works for me. Thanks @jsilvestre .
