### ISSUE TITLE
Remove message with trash in mail content seems broken.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#229]
If I try to remove only one message in a conversation (with trash in right), I receive this error: 
```
PATCH https://bellot-zoe.cozycloud.cc/apps/emails/message/883f98d550b30fe64ed500538397b417 [HTTP/1.1 500 Internal Server Error 7139ms]
"Error in messagePatch" "883f98d550b30fe64ed500538397b417" "Error: socket hang up"
```

**Comment by clochix** [comment]
I'm unable to reproduce, could you paste the error in the logs of the server ?

**Comment by frankrousseau** [comment]
I had an error message too last time I deleted several messages. But I didn't save the content.

**Comment by clochix** [comment]
Could you please try to provide some logs next time you face this bug ?

**Comment by frankrousseau** [comment]
ok

**Comment by clochix** [comment]
This is related to the way we decide which messages belong to a conversation. I think messages in trash are still displayed inside the conversation. Also, if you go to Trash and select the deleted message, you may see all messages, even those not deleted (not sure).
