### ISSUE TITLE
Can't navigate in message list after a message deletion with keyboard

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#230]

**Comment by clochix** [comment]
Please try to delete / move conversations and see if there's still a selected message after its done.

**Comment by poupotte** [comment]
When I delete a message I can navigate in my message list but it breaks the interface :/ :

![interface_cassee](https://cloud.githubusercontent.com/assets/2659119/6870817/be43c2c8-d49e-11e4-8d28-6d6c636a2fa4.png)

**Comment by poupotte** [comment]
I opened a new issue for the specific problem decribe over it. Thansk @clochix .
