### ISSUE TITLE
Add 2 different fields for login and address

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#232]
In version 0.6.9 of email app, there is only one field for login and adress. The problem is the following : 
- when filling adress with login@domain.tld, the connection to the imap/smtp server is not possible if the login is not the full adress
- when removing the @domain.tld, IMAP/SMTP servers are not filled automatically, and it is not possible to send an email, as there is no valid adress specified.

Proposal : 
- Add a second field "login"
- When address is filled in the form, login field is filled with the same value as address
- Login can be modified without impact on address

This should have inpact on couchDB structure (a new field adress could be necessary)

**Comment by ZeHiro** [comment]
Hello,
do you have any plan to fix this?
I currenly cannot use the mail app to write mails (just reception).
Thanks

**Comment by clochix** [comment]
Hello ZeHiro,
good news, this is in progress, see #84. Should be available in next version.

**Comment by ZeHiro** [comment]
Cool. Thank you for the fast answer.
Good job on all the cozy project.

**Comment by poupotte** [comment]
It's available on development branch. @ZeHiro, you can already test it if you installe emails in 'development' branch or wait the next version (at the end of next week).

**Comment by ZeHiro** [comment]
@poupotte , I 've installed the dev branch, but it does not seem to work.
I tried to update the mail account (so I didn't create one), and the Check of the connection fails. 
It is like the imapLogin Field is not taken into account in the check of the connection, before enabling to save the new parameters.

Another bug I noticed : french locale for "Utilisateur IMAP (s'il est différent du login)" should be "Utilisateur IMAP (s'il est différent de l'adresse mail)"
The same for the SMTP login (not clear)

**Comment by clochix** [comment]
My bad, checking the connection uses a different code path, where imapLogin wasn't used. I'll fix this and come back to you.
Could you try to save the account without checking the parameters, and tell me if it works ?

Thanks for your suggestions, I've updated the labels.

**Comment by ZeHiro** [comment]
The imap logins and smtp logins were store in the DB, but I cannot check if this really works, as I cannot save the address : when saving the address, a connection check is done, and fails.

So I still don't have a proper mail saved in the "login" field of the DB, I cannot check : 
- if the right login is used to connect to imap
- the right login is used to connect to smtp
- I cannot test sending an email.

**Comment by ZeHiro** [comment]
I forked the app and added https://github.com/clochix/cozy-emails/commit/5e07ed27ca7a01b92c48f76a873a9ccf26c2d8f3 commit.
And it works fine now. 
Thank you

**Comment by clochix** [comment]
Thanks a lot @ZeHiro ! The code will be in the next official version of the application ☺

**Comment by clochix** [comment]
@poupotte I think you can test by setting a wrong user address, your real one in IMAP Login field, and checking connection.

**Comment by poupotte** [comment]
Thanks @clochix, I'll test it :)

**Comment by poupotte** [comment]
It seems work for me, thanks @clochix .
