### ISSUE TITLE
Improve loading indicator

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-emails#233]
After investigating https://github.com/cozy/cozy-emails/issues/226, I realize the issue was the user thinks there is a bug because the spinner spins for a very long time. We should re-think that.

**Comment by jsilvestre** [comment]
I would add that there is more than just the spinner spinning: when a user triggers the refresh, it takes a short time before the spinner starts spinning. This gives an impression of slowness in the UI.

It is even worse if there is an error, because it's longer, because it must wait for the imap connection to timeout, which is very disturbing for the user.

**Comment by poupotte** [comment]
Refs #305
