### ISSUE TITLE
Remove toastr to indicate that draft is saved.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#236]
When I compose an email,  'Message saved' are regularly displayed. Button 'save' should be indicate this information : 

* `Save` can become `Saved`
* Button `Save` can displayed as `Cancel` button and can be blue or grey if draft is saved or not.

**Comment by poupotte** [comment]
Notification is well removed. Thanks @clochix .

For a next version, it should be nice to display `Saved` (with inactive button) instead of `Save draft` after draft saving. But I suppose is not easy because this state is avaible only between the save and the next user modification on his draft.

**Comment by clochix** [comment]
As a user, I'd like so to be able to save the message “by hand”, by clicking on the save button. So I'm not a big fan of updating its label (or just for a few seconds) and disabling it. What do you think ?

**Comment by poupotte** [comment]
I agree with you to allow to save 'by hand', I proposed to display 'Saved' on inactive button between the end of automatic save and the next modification (or 2 seconds after automatic save). 
Indeed, the spinner on button is displayed very quickly, so I'm not sure, user see it.

**Comment by clochix** [comment]
I don't have a big screen, so most of the time buttons are outside my viewport when I reply to a message. I don't see spinner, but wouldn't see a label change on the button.

**Comment by frankrousseau** [comment]
@clochix Can you provide a screenshot about your screen issue? I think it would help @m4dz for his layout rebuilding.

**Comment by clochix** [comment]
![layout](https://cloud.githubusercontent.com/assets/384908/7113701/af3ea26c-e1d6-11e4-9e51-41468beb7580.png)

**Comment by frankrousseau** [comment]
Thank you, it's a lot clearer now!
