### ISSUE TITLE
"Reply-To" not used when replying

### ISSUE THREAD

**Issue by AntoineCa** [cozy/cozy-emails#249]
When a received message contains the PHP ["Reply-To" header](http://php.net/manual/en/function.mail.php#example-3588), the application still responds to the address specified in the "From" header.

**Comment by clochix** [comment]
I just had a look at this, it seems to be a server-side bug : replyTo field is always empty. Mailparser should return it, but if it doesn't, we must parse `headers` array to get it.

**Comment by clochix** [comment]
My bad, Mailparser returns the fields, we had a typo in our code that prevented to save it. Should be fixed in next release, thanks @AntoineCa for reporting it ☺

**Comment by poupotte** [comment]
It works for me. Thanks @clochix .
