### ISSUE TITLE
Handle better unknown contacts

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#259]
When I write an unknown email into the recipient input key, the enter key doesn't add it to the recipient list.

#258 should fix it.

**Comment by poupotte** [comment]
When I try to add `test@cozycloud.cc` in the recipient input (unknown contact) : I enter `test`, then when I try to add `@`, application display a pop-up 'The given email is unproperly formatted: test'. I think when I click on `Atl Gr`, application checks user mail so I can't enter user mail.

**Comment by frankrousseau** [comment]
Ok. What are your distribution and browser ? (It works fine on my computer both in Firefox and Chrome).

**Comment by poupotte** [comment]
I have Ubuntu 14.04, it works on chrome but not on firefox for me.

**Comment by frankrousseau** [comment]
What is wrong is that it checks the emails on blurring.

**Comment by frankrousseau** [comment]
I think it's fixed. Could you check again?

**Comment by poupotte** [comment]
It works well now, thanks @frankrousseau
