### ISSUE TITLE
Ui: Conversation view

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-emails#263]
_Note: This issue resume #255_

# Revamp
* Conversation view
    * improve semantics by isolating components in markup (section, article, header, nav…)
    * add a toolbar component that handles _large view_, _prev_/_next_ navigation
    * isolate conversation subject to top header
* Messages stack in conversation
    * messages are now stacked with a compact header (sender infos, date and indicators)
    * if the stack length is > 3, then only load first and last message from the stack and add a button to load the full stack (in compact mode)
    * a click on compact header will toggle the message view (compact or full)
* Message view
    * header display only sender and recipients
    * _from_ label is removed
    * indicators are only displayed in header (no more links)
    * details box is available to display more header informations
    * toolbar is now right-aligned and buttons are correctly marked / grouped
    * all buttons in toolbar now uses dedicated icons
    * a subbar in footer is available for quick-reply actions (a quick reply compose box can be a nice improvement)
    * attachments are now displayed in footer with a visualisation link and a download link
    * attached images are displayed as thumbnail in footer (a real thumbnail generator can be a nice improvement)

# Global Style
* toolbars use the bootstrap style
* messages stack and message view now use a card-style
* `pre` markup uses the given _Source Code Pro_ font

# Known bugs and temporary disabled features
* contact tooltip (_Participant_ component) is temporary disabled because it needs to be revamped, with preview box and quick-add features
* the message iframe seems to be too high
* the large messge view switch is currently broken, it will be fixed in another PR

**Comment by poupotte** [comment]
It's very nice :) 
Good job, I'm really surprised of result !

Some remarks/questions : 
* When a contact hasn't photo (because is unknown for exemple), it's displayed in black instead of blue (in message stack conversation), is it wanted? Maybe it's due to disable of contact tooltip.
* I would add a line 'Move to...' at the beginning of menu (folder button).
* There isn't tooltips on button, it's for an other PR ?
* Attachments seems available only at the end of mail. Why not use paper clip as a button ?

**Comment by m4dz** [comment]
> Good job, I'm really surprised of result !

Thanks a lot!

> Some remarks/questions :
> * When a contact hasn't photo (because is unknown for exemple), it's displayed in black instead of blue (in message stack conversation), is it wanted? Maybe it's due to disable of contact tooltip.

Yep, that's it. I'll produce quickly the component, probably with @Benibur whose want to contribute to this part.

> * I would add a line 'Move to...' at the beginning of menu (folder button).

Good idea, I'll do this.

> * There isn't tooltips on button, it's for an other PR ?

Of course :stuck_out_tongue_winking_eye:

> * Attachments seems available only at the end of mail. Why not use paper clip as a button ?

Yep, I think I'll add a popup like for the _detailled headers_ that'll also list attachment for saving.

@frankrousseau and others also notice the following:
* when collapsing/expand a messages, the margin made an uncomfortable effect
* the contrast for the alert box about remote content (images) is too low
* dates need a better solution (I have already opened #266)

I prepare a PR for this fixes.

**Comment by frankrousseau** [comment]
when collapsing/expand a message => it bugs and the conversation panel vanished.

**Comment by poupotte** [comment]
It's well for me. Thanks @m4dz :)
