### ISSUE TITLE
Ui: Layouts

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-emails#264]
We need a more robust way to handle panes layouts:
* use flexbox to manage their layout
* keep menu-pane in two-modes: compact and expanded. No need for this pane to be proportionnal
* extract notification container from panes to attach it to `document.body`
* manage RWD with following modes:
    * small screens: menu in a drawer ; list in main view ; conversation view in overlay
    * medium screens: menu in compact mode + list in main view ; conversation view in overlay
    * large screens: 3 panes, list and conversation view at width 50%
    * extra-large screens: 3 panes, list with a max-width

**Comment by m4dz** [comment]
Here is the doc concerning the layouts. The sketches below represent different view modes.

![emails app layouts sketches](http://f.cl.ly/items/3y082l22251A2b072p3s/Image.png)

Basically, it is a composition of two elements: `menu` and `mailbox-zone`. The two can be displayed in different modes:
- menu
    - `expanded=false`: this is a compact mode, with only main icons available
    - `expanded=true`: this is the full mode with all icons and subparts
- mailbox-zone
    - `layout=horizontal`: split the zone horizontally with messages-list on top and conversation below
    - `layout=vertical`: split the zone vertically with conversation right of messages-list

Concerning RWD layouts:
- on small screens: menu is always expanded (but masked in a drawer), layouts are ignored
- on medium screens: menu supports both modes (expanded || collapsed) (always in a drawer), layouts are ignored
- on large screens: menu supports both modes, layouts are applied
- on xtra-large screens: like on large screens, but message-list have a max-width applied in vertical layout

It can be translated to the following CSS rules:

```stylus
#menu
    // defaults styles in full mode
    media(min-width: 321px)
        // elements only visible on large screens (compose button, etc)
        [aria-expanded=false]
            // compact mode rules

#container
    // flexbox layout rules
    media(min-width: 321px)
        #panes
            // set margin to display menu in compact-mode + drawer
    media(max-width: 768px)
        // set rules for drawer
        #menu[aria-expanded=true] + #panes
            // set the _open_ mode for the drawer
    media(min-width: 769px)
        &.layout-h
            // horizontal split rules
        &.layout-v
            // vertical split rules
    media(min-width:1281px)
        &.layout-v #message-list
            // max-width for message list
```

Notes:
- breakpoints _must_ be declared in `em` to be truly responsive (`px` are just for convenient read)
- those rules does _not_ treat the way panes works (especially with overlay conversation view in small and medium screens – see sketches)
- CSS transitions will so be applied for show/hide components such as menu drawer or conversation view

**Comment by frankrousseau** [comment]
I like the way you handle responsive. But I don't see any sketch of a zen mode. I know it's a nice to have but that's something I would like to have to write my emails.
