### ISSUE TITLE
Ui: Menu view

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-emails#265]
Menu view wants to be restyled with:
* do not use a proportional screen width but use only needed-space (see #264)
* change background-color to stick to cozy-apps style (whatever it means :tongue:)
* defines toolbar / subbar:
    * toolbar: new mail / refresh all accounts
    * subbar: add account / settings
* make folders tree more readable (review indents)
* groups important boxes at top
* display _Archive_ box as a special folder?
* only display a background-color on main box (inbox) and remove it on others
* remove progress bar and use a svg gauge

**Comment by frankrousseau** [comment]
I add:

* Extract the compose button to put it on top right of the message list.
