### ISSUE TITLE
Mark mails as read often fails

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#274]
When I navigate in my message list. Mails are well displayed read but often, just after messages are display unread/read/unread.

Most of messages change 2 or 3 times of state. (read -> unread or read -> unread -> read).

**Comment by frankrousseau** [comment]
+1 I noticed the same problem.

**Comment by clochix** [comment]
I'm waiting for #132 (which implies some refactoring of the frontend affected code) before having a look at this one.

**Comment by poupotte** [comment]
It works perfectly \o/ !!!

Thanks @clochix .
