### ISSUE TITLE
Contact drag and drop doesn't work well

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#281]
I can move my contact from 'To' to 'CC'. But If I move my contact from 'CC' to 'To' it disappear.

**Comment by clochix** [comment]
This should also fix a second bug : dropping a contact over its source field deleted it.

**Comment by poupotte** [comment]
Mmmm... I have a strange behavior:
I move my contact from 'To' to 'CC' then from 'CC' to 'To'. Contact label disappears but if I type a character in input 'To' my contact label re-appears. (Same behavior on Firefox and Chrome)

**Comment by poupotte** [comment]
It works well now, thanks @clochix
