### ISSUE TITLE
Have a look at picture import inside the RTE

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#288]

**Comment by clochix** [comment]
The first step is done, I investigated and know how to add an image to a message from an external source. It works for now with Web Activity to import an image from the File app, I need to work with @Benibur to use its popup that allows to select images from the photo application.

We should also handle the images dropped into the editor from the window manager of the user. I have some code for this, but it needs refactoring. Should I open another ticket, or do we keep this one ?

**Comment by clochix** [comment]
I added this to current sprint, as I already did half of the work for the image drag and drop inside editor, and would like to finish it.

**Comment by frankrousseau** [comment]
@clochix It's better if you fix current issues (realted to quick search). Demo day is thursday.

**Comment by clochix** [comment]
@poupotte could you give it another try, I hope I fixed the bug you hit during demo.

**Comment by poupotte** [comment]
It works well even if focus isn't on content mail. Thanks @clochix
