### ISSUE TITLE
Spam folder emails displayed as not read

### ISSUE THREAD

**Issue by pierrerousseau** [cozy/cozy-emails#292]
Hi,

I just updated my email app this morning, it's a very nice improvement. However, it adds new bugs :p 

This one is a bit annoying : now the spams from my gmail account are displayed as "not read" so I have something like 350 emails not read all coming from the spam folder (created by gmail i guess). And I get notifications for this.

This folder does not belong to my favorites, so I think a good way to solve this would be to display only the new emails from the favorites folders.

**Comment by aenario** [comment]
Hi @pierrerousseau , 

I agree that including messages from trash & spam/junk in the account unread count is a problem and we will fix it.  

However, for my personal use case, I have a number of filter boxes (like github, couchsurfing, amazon) that are automatically filtered, I dont want them in my favorites, but i want to know when there is unread mail in them.

**Comment by frankrousseau** [comment]
The other important aspect of the bug is that it pops new email notification every hour. Romain tell me if it's hard to solve. We should fix it quickly, it is very annoying.

**Comment by aenario** [comment]
Mmh, it should pop notification only if you received new emails during the hour. Otherwise its a bug !

**Comment by frankrousseau** [comment]
A you'right I have new emails often. Because the number is totally irrelevant, I thought it was a bug.

**Comment by poupotte** [comment]
It's ok for me. @pierrerousseau, your problem should be fixed in the next version.
