### ISSUE TITLE
Unable to re-open message preview after closing it

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#298]
Reported by @Abbo44 : when he closes a message preview with the arrow on top left, selecting another message doesn't display its preview.
Seems like a regression.

**Comment by clochix** [comment]
@m4dz in fact, this one is for you, it's related to the layout : instead of toggling fullscreen, the arrow on the upper right corner closes the preview and prevent from re-opening it. I think you will fix this when working on the layout.

**Comment by frankrousseau** [comment]
Yes M4dz told me it's related to panel management.

**Comment by jsilvestre** [comment]
Apparently it's fixed, thanks to #260
