### ISSUE TITLE
Display error after an update

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#300]
If I update my application, when I return on my application, I have an error 'Argh, I'm unable to perform this action, please try again'. A refresh removes it.
Sometimes, it displays error also after a restart.

**Comment by clochix** [comment]
Next time, could you have a look at server logs, to get the full error message ? Thanks ☺

**Comment by poupotte** [comment]
I haven't errors in server logs :/ .

**Comment by poupotte** [comment]
This issue seems fixed. I close issue.
