### ISSUE TITLE
Problem with reply-all

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#303]
If I receive a message from a mailing-list, first message is : 
    **From:**  `Contact x`
    **To:** `ML`

If I reply, draft has `Contact x` as recipient : OK
If I reply-all, draft has `Contact x` as recipient : KO -> It should be `Contact x` and `ML`

**Comment by clochix** [comment]
This is an annoying UI bug : ML is added to recipients in cc field, but this filed is hidden. I'll fix it.

**Comment by poupotte** [comment]
It's fixed, thanks @clochix .
