### ISSUE TITLE
More information on fetching email process

### ISSUE THREAD

**Issue by pierrerousseau** [cozy/cozy-emails#305]
It would help to have information about what is happening when cozy-mail fetch emails.

For now, there is only a loader icon, without even a tooltip telling what it is about. 

If you don't want to add information on the page, a tooltip would help : something saying what is this icon when nothing is happening, and when the loader is displayed what mailbox is being refreshed (otherwise it's just running without giving any idea of the state of the process).

**Comment by frankrousseau** [comment]
+1

**Comment by poupotte** [comment]
It works for me. Thanks @jsilvestre . 

Information displaying can shift left menu width but we correct this issue with #265 .

**Comment by jsilvestre** [comment]
Yes I figured that would be fixed quickly...just did the minimal required painting. Can't wait to see it properly styled.
