### ISSUE TITLE
Contact labels on the same line than input in mail composition

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#321]
In mail composition, it should be nice to have contact labels on the same line than input (see tags in contact as an example).

![contact_label](https://cloud.githubusercontent.com/assets/2659119/7175653/49faed64-e417-11e4-8287-6ca01ddc38d0.png)

**Comment by jsilvestre** [comment]
https://github.com/chenzihui/react-tokenizer is the way to go (or could be use as a source of inspiration).

**Comment by poupotte** [comment]
It works well. Thanks @clochix .

**Comment by clochix** [comment]
In fact, @aenario pointed some problems with Chromium, so I did some fix which will be merged in #517.

**Comment by poupotte** [comment]
Ok, thanks. I've tested only on Firefox.
