### ISSUE TITLE
Improve all confirmation dialogs

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#326]
In my mind, we have the choice between : 
* Improve this pop-up (design + message)
* Remove this pop-over: save draft by default with a toastr to undo saving.

I think, the first solution is better for now. If pop-up is still annoying after that, we could remove it.

**Comment by clochix** [comment]
To improve the confirmation dialog, I had to do some refactoring, so:
 - I replaced every call to `window.confirm` by a popin window ;
 - I refactored some components.

You should try:
 - the confirmation dialog when expunging trash mailbox;
 - the confirmation dialog when deleting messages / conversation;
 - the dialog when canceling a draft. When deleting a draft;
 - the window when there's error refreshing a mailbox (hard to reproduce).

**Comment by poupotte** [comment]
Confirmation dialogs are better like that. However, there are some issues : 
* When I delete a conversation (with keyboard shortcut) : I see a window.confirm
* When I delete a message : I have message for expunging trash mailbox
* Title and message are identical in modal : 
![confirm_modal](https://cloud.githubusercontent.com/assets/2659119/7883891/425ed1ea-061a-11e5-873e-146bc29a21b5.png)

**Comment by poupotte** [comment]
Thanks @clochix for changes, it works well :)
