### ISSUE TITLE
Send is broken

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#327]
At yesterday demo, the email sending failed (showed a popup to save a draft). Sending an email should work in any case.

**Comment by frankrousseau** [comment]
@poupotte @aenario @clochix This one is really important.

**Comment by clochix** [comment]
The “draft” flag was not removed when message was sent, so sending a message that was previously saved as draft triggered the cancel draft dialog.

**Comment by poupotte** [comment]
Seems work for me, thanks @clochix
