### ISSUE TITLE
Problem with interface in draft composition

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#328]
When I compose my draft (normal interface) : 
![composition](https://cloud.githubusercontent.com/assets/2659119/7176649/87360bba-e420-11e4-8d77-c3bec65e1ca2.png)

When I leave my composition page (left pannel moves) : 
![composition_confirm](https://cloud.githubusercontent.com/assets/2659119/7176665/989ce842-e420-11e4-9580-d94f3fb5e6bf.png)

After I confirmed my draft saving (messages list is shifted up) : 
![composition_end](https://cloud.githubusercontent.com/assets/2659119/7176680/b75ad910-e420-11e4-921a-72cc1b2db9ba.png)

**Comment by christi9n** [comment]
Many thanks ;o)

**Comment by poupotte** [comment]
This problem is a home issue.
