### ISSUE TITLE
Add simple search

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#329]
Add search on : 
* recipient
* sender
* dates
* the beginning of title

**Comment by clochix** [comment]
After speaking with @poupotte and @aenario, we won't do filtering on subject in this sprint, because we need to use the indexer for this one. Using only CouchDB views make the messaged sorted by subject, not date.

**Comment by poupotte** [comment]
**Date :** 
It works but if I select from x to y, it doesn't display messages received the y day. In my mind, these messages should be included.

**Recipient / Sender :**
It seems work but messages aren't sorted by date.

**General :**
 * When I left filter page, my messages in my classic messages list aren't sorted by date.
 * If I open an email after a filter and then I search on other filter, I receive this error : 
```
"Error in fetchMessagesByFolder" Object { message: "{ error: 'query_parse_error: No rows can match your key range, reverse your start_key and end_key or set descending=false' }", stack: "Error: { error: 'query_parse_error: No rows can match your key range, reverse your start_key and end_key or set descending=false' }
    at /usr/local/cozy/apps/emails/node_modules/cozydb/lib/cozymodel.js:252:27
    at parseBody (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/emails/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)" }
```

**Comment by poupotte** [comment]
It works well, thanks @clochix
