### ISSUE TITLE
Errors in server logs after account deletion

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#341]
It seems like server tries to refresh deleted accounts, I get this errors in logs: 

    EROR models:account CANT REFRESH ACCOUNT Youpi { [NotFound: Not Found: Account#a9a9c063258e6198975a955722188b0f]
      name: 'NotFound',
      status: 404,
      message: 'Not Found: Account#a9a9c063258e6198975a955722188b0f' }

**Comment by aenario** [comment]
This should have been fixed in latest version.
