### ISSUE TITLE
Wrong error message on IMAP timeout

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#350]
Checking the parameters of a GMail account, we get the message “Wrong IMAP TLS”. It seems that the error message is wrong, according to https://github.com/cozy/cozy-emails/blob/master/server/imap/pool.coffee#L238

**Comment by clochix** [comment]
@poupotte dou you know if we can close this one?

**Comment by poupotte** [comment]
This issue should be improved, but I'm not sure that it's totally fixed. We have to test ...

**Comment by poupotte** [comment]
This issue should be fixed.
