### ISSUE TITLE
New email account auto-configuration

### ISSUE THREAD

**Issue by Kloadut** [cozy/cozy-emails#354]
It would be awesome, as said in the last user meeting, to have an auto-configuration at account creation, based on the email address.

2 different ways to implement it:

* (Simple) Retrieve configuration for common providers (Gmail, Yahoo, Live, etc.)
* (Complex) Use the Thunderbird mechanism: https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

**Comment by clochix** [comment]
As also said in the last user meeting, we already follow the easy way, by checking Thunderbird's provider database. So account configuration is already set for all major providers.

**Comment by Kloadut** [comment]
Oh great! Sorry then :)
