### ISSUE TITLE
Wrong styling of sent message

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#360]
Paragraphs are not properly rendered by Thunderbird, the margins are too big.

**Comment by poupotte** [comment]
It doesn't work for me :/

Sent message (in Cozy):
![message_sent](https://cloud.githubusercontent.com/assets/2659119/7346845/ad00d38c-ece2-11e4-94a3-ef052de888f0.png)

Received message (in Thunderbird):
![message_received](https://cloud.githubusercontent.com/assets/2659119/7346852/bb7e755e-ece2-11e4-8897-c4b2141c7340.png)

**Comment by frankrousseau** [comment]
Do you use Thunderbird in text mode ?

**Comment by clochix** [comment]
FTR, I previously hacked MediumEditor to insert BR instead of paragraphs when hitting return, but this changes where lost some weeks ago when I updated the lib.
I've just restored them and will push them ASAP.

**Comment by frankrousseau** [comment]
I think it will break my changes. I relied a lot on paragraphs. I will merge and make more testing.

**Comment by frankrousseau** [comment]
Ok I tried with the latest version and it works. Could you try again @poupotte and tell me if you are in text mode?

**Comment by poupotte** [comment]
Yes, I'm in palin text : 

Original html : 
![original_html](https://cloud.githubusercontent.com/assets/2659119/7365917/cf01b4d0-ed94-11e4-8ff1-62979b516d66.png)


Simple html :
![simple_html](https://cloud.githubusercontent.com/assets/2659119/7365920/d3347ce0-ed94-11e4-9a32-41ea6f6b99cd.png)

Plain Text : 
![text_plain](https://cloud.githubusercontent.com/assets/2659119/7365931/e19fe27e-ed94-11e4-8d02-868ea73a816b.png)

In Cozy : 
![cozy_2](https://cloud.githubusercontent.com/assets/2659119/7365966/28a56e14-ed95-11e4-919a-cf5dc51c9e27.png)
![cozy_1](https://cloud.githubusercontent.com/assets/2659119/7365965/28a49584-ed95-11e4-8398-63ebd33821f6.png)

**Comment by frankrousseau** [comment]
Ok. Can you tell me which version of Thunderbird you have?

**Comment by poupotte** [comment]
31.6.0

**Comment by poupotte** [comment]
Sourrce code for my mail : 

```
Return-Path: <mymail>
Delivered-To: mymail
Received: from b0.ovh.net (HELO queue) (213.186.33.50)
	by b0.ovh.net with SMTP; 28 Apr 2015 10:45:20 +0200
Received: from localhost (HELO mail439.ha.ovh.net) (127.0.0.1)
  by localhost with SMTP; 28 Apr 2015 10:45:20 +0200
Received: from b0.ovh.net (HELO queueout) (213.186.33.50)
	by b0.ovh.net with SMTP; 28 Apr 2015 10:45:20 +0200
Delivered-To: cozycloud.cc-mymail
Received: from b0.ovh.net (HELO queue) (213.186.33.50)
	by b0.ovh.net with SMTP; 28 Apr 2015 10:45:19 +0200
Received: from localhost (HELO mail439.ha.ovh.net) (127.0.0.1)
  by localhost with SMTP; 28 Apr 2015 10:45:19 +0200
Received: from b0.ovh.net (HELO queueout) (213.186.33.50)
	by b0.ovh.net with SMTP; 28 Apr 2015 10:45:19 +0200
Received: from prox-int-02.cozycloud.cc (HELO ?127.0.0.1?) (mymail@176.31.231.103)
  by ns0.ovh.net with SMTP; 28 Apr 2015 10:45:13 +0200
Content-Type: multipart/alternative;
 boundary="----sinikael-?=_1-14302106223740.3087270960677415"
From: zoe <mymail>
To: Moi <mymail>
In-Reply-To: <>
Subject: Test
X-Mailer: nodemailer (1.3.0; +http://www.nodemailer.com;
 SMTP/0.1.13[client:1.2.0])
Date: Tue, 28 Apr 2015 08:43:42 +0000
Message-Id: <1430210622809-c55a83ca-28fce019-a2854499@cozycloud.cc>
MIME-Version: 1.0
X-Ovh-Tracer-Id: 5231212443444084239
X-Ovh-Remote: 176.31.231.103 (prox-int-02.cozycloud.cc)
X-Ovh-Local: 213.186.33.20 (ns0.ovh.net)
X-OVH-SPAMSTATE: OK
X-OVH-SPAMSCORE: 0
X-OVH-SPAMCAUSE: gggruggvucftvghtrhhoucdtuddrfeektddrieelucetufdoteggodetrfcurfhrohhfihhlvgemucfqggfjnecuuegrihhlohhuthemuceftddtnecu

------sinikael-?=_1-14302106223740.3087270960677415
Content-Type: text/plain
Content-Transfer-Encoding: 7bit


p {margin: 0;}
pre {background: transparent; border: 0}^8


1

2

3

4

5
678

--
--
undefined

------sinikael-?=_1-14302106223740.3087270960677415
Content-Type: text/html
Content-Transfer-Encoding: 7bit

<style type="text/css">
blockquote {
    margin: 0.8ex;
    padding-left: 1ex;
    border-left: 3px solid #34A6FF;
}
p {margin: 0;}
pre {background: transparent; border: 0}
</style>
<head><style>
p {margin: 0;}
pre {background: transparent; border: 0}^8
</style></head><body><p style="margin: 0">1</p><p style="margin: 0">2</p><p style="margin: 0">3</p><p style="margin: 0">4</p><p style="margin: 0"><br></p><p style="margin: 0">5<br>678<br></p><p style="margin: 0"><br></p>
<p id="signature">--
--<br>undefined</p></body>
------sinikael-?=_1-14302106223740.3087270960677415--

```

**Comment by frankrousseau** [comment]
I think this fix should be removed from the sprint. I won't have the time to perform it for this afternoon. 
Sorry for the wrong estimation.

**Comment by poupotte** [comment]
I haven't anymore 'p {margin} ...' on text mode.
However I still wrong paragraph on text mode and simple HTML.

**Comment by frankrousseau** [comment]
Yes I removed the style header. Now we are in the same state as before.

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
