### ISSUE TITLE
Deleting several emails should lead to a single notification

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#412]
When I delete several emails, it displays many notifications. It should display only one notification for the whole batch.

**Comment by poupotte** [comment]
It seems work for me.

It displays one notification by email or several notification as 'x conversation deleted' ?

**Comment by frankrousseau** [comment]
One by email.

**Comment by frankrousseau** [comment]
It works for me too. If it happens again I will repoen the issue. Sorry for the inconvenience.
