### ISSUE TITLE
Canceling a draft creation should not display warning when the draft is empty

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#414]
When I cancel a wrong reply it asks me to confirm that I want to cancel it. It's annoying, especially when coding on reply features.

**Comment by clochix** [comment]
Shall we display the confirmation message only when message content is not empty or when message content has not been updated (ie when you hit reply, then cancel without altering message content, should we display the confirmation message ?)

**Comment by frankrousseau** [comment]
Both case sounds good.

**Comment by poupotte** [comment]
It seems work for me. Thanks @clochix .
