### ISSUE TITLE
Expeditor filter should apply to contact name too

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#416]
Currently when filtering on a sender, it only search on the email. Searching on the contact name would be great too.

**Comment by clochix** [comment]
Have you an example which doesn't work ? (FTR, filtering is based on CouchDB, so the real meaning of the filter is “name or address starts with…”)

**Comment by frankrousseau** [comment]
"Luc Collin" as name and "jlcollin" as email.

**Comment by clochix** [comment]
I'm able to display an email sent by "Luc Collin" <jlcollin@xxx> by filtering either on "Luc Collin" or "jlcollin"

**Comment by clochix** [comment]
We filter on the name and address in the message filter. Did you mean that if the sender is in your address book, you also would like to filter on its name there ?

**Comment by frankrousseau** [comment]
Now it works. If I still meet the problem I will open the issue again. Sorry for the inconvenience.
