### ISSUE TITLE
empty error message while setting up email

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-emails#417]
After getting errors on the imap port, I changed some settings, tried the check connection button again and got an empty red box and so fields highlighted. 

![screenshot from 2015-05-04 10 38 24](https://cloud.githubusercontent.com/assets/108437/7450824/cc0501e2-f249-11e4-97d8-3955ef610e0a.png)

**Comment by clochix** [comment]
I'm unable to reproduce this one, so I updated the code at the only place I found where an empty notification may be thrown. I also prevented empty notifications to show up. Instead, the app will throw an exception that we can get in server logs to ease debug next time it happens.

**Comment by arthurlutz** [comment]
Should cozy-email work with self signed certificates ?

**Comment by clochix** [comment]
@arthurlutz I think that by default, Cozy will reject self-signed certificates.

The libraries we use allow to set advanced TLS options, so we should be able to allow the user to ask not to reject self signed certificates, or to register its certificate.

**Comment by clochix** [comment]
In fact, I just saw in the code that we already allow self-signed certificates: https://github.com/cozy/cozy-emails/blob/master/server/imap/pool.coffee#L78
@aenario, could you confirm ?
IMHo, this is not secure, and we should add an option so user can choose to accept or reject untrusted certificates.

**Comment by frankrousseau** [comment]
@aenario is in vacations. He will come back on monday.
