### ISSUE TITLE
Make the menu items horizontal

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#42]
It would allow to display more boxes without scrolling.

**Comment by poupotte** [comment]
Maybe, we can add an 'help' in configuration with a list of keyboard shortcut.

**Comment by clochix** [comment]
This is not really related to keyboard shortcuts, there's now a layout setting in configuration, allowing to choose a three panes layout.

**Comment by poupotte** [comment]
I think, we can close this issue, the menu items horizontal works well and we have, now, enough documentation to use this option. Are you ok @frankrousseau ?

**Comment by frankrousseau** [comment]
I can't see any documentation about that.

**Comment by clochix** [comment]
@frankrousseau what kind of documentation would you like ?

**Comment by frankrousseau** [comment]
I finally found the `atl+w` command. The left column seems super-large to me. But it looks to work.

I think the settings screen should display much more information about different settings. We could add something about shortcuts.

The colon settings doesn't seem to work when you use the shortcut.

**Comment by clochix** [comment]
You can select the three columns layout in Settings, without keyboard shortcut. I agree we should display more information on settings, I created #152 for this purpose.

**Comment by frankrousseau** [comment]
OK let's close that one.
