### ISSUE TITLE
New mails are diplayed in filter

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#426]
As an example : I filter my message to display only mails received two month ago. I receive a new message, it is displayed in the beginning of the messages list.

**Comment by clochix** [comment]
I see two ways to fix this problem:
 - easy path: don't show new message when list is filtered (except maybe if it's filtered on unread messages) ;
 - better but harder: apply filters on client side to new messages.

The second is not really hard, but I wonder if it's worth going this path. What do you think ?

**Comment by poupotte** [comment]
In my mind, first path is enough. If you just can do an exception for unread filter, it's perfect :)

**Comment by poupotte** [comment]
It works well ! Thanks @clochix  :)
