### ISSUE TITLE
Keyboard navigation in message list doesn't start infinite scroll

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#427]
If I navigate in my messages list with keyboard, when I arrive at the end of the list, it stops at the last message. Thus, `Display more messages` isn't displayed and so application doesn't retrieve next messages. Scroll my list with my mouse is enought to trigger messages retrieval.

**Comment by poupotte** [comment]
Infinite scroll works well with keyboard navigation. Only one detail, we can't see spinner. It would be better if user see it to know that scroll is started. Is it difficult to display it ?

**Comment by clochix** [comment]
It's not a bug, it's a feature ! I now fetch next messages earlier (when last message is displayed, instead of when “more messages” appears), so the user wait less before getting them.
I'll add some margin under current message, to display the spinner.

**Comment by poupotte** [comment]
It works well ! Thanks @clochix :)
