### ISSUE TITLE
When the compose widget is displayed, it should focused on the right field

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#43]
The `to` field when it's a new email.

The `content` field when it's an answer.

**Comment by frankrousseau** [comment]
It works well in top mode. But it doesn't work in bottom mode. Should we remove the bottom mode?

**Comment by poupotte** [comment]
It's same for me, bottom mode doesn't work (top mode works).

**Comment by clochix** [comment]
This is a dramatic regression, I'm working on it, it's the main feature a decent email client should provide.

**Comment by poupotte** [comment]
It works for me.

**Comment by frankrousseau** [comment]
Yes it works, but it still requires improvement to be useable: the cursor is displayed at the bottom of the page, it makes it hard to find.  Two suggestions to fix that problem:

* The compose area should not be so big (I mean it get as long as the answered email is, with long mails it make the area really too big).
* The automatic scroll should be performed on it instead on the main window.

**Comment by poupotte** [comment]
Thanks @clochix,  it works well. 
It's ok for you @frankrousseau ?

It will be available in **version 0.6.8**

**Comment by frankrousseau** [comment]
Yes it's a lot better. Thank you all.
