### ISSUE TITLE
Enable configuration of login for imap for use case when email != login

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-emails#434]
To get my email account to work I had to say email = "arthur" instead of email = "arthur@example.org" since my imap server seemed to be saying that it did not know arthur@example.org... this is probably a misconfiguration of my imap server but in case it isn't one should be able to have this advanced setting while setting up email on cozy

**Comment by clochix** [comment]
We just did it in #232, should be available next week ☺

**Comment by poupotte** [comment]
@arthurlutz , It should be available on new email version. Don't hesitate to reopen this issue if it doesn't work for you.
