### ISSUE TITLE
Generated error when emptying Trash on initial import

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-emails#435]
After configuring cozy-emails could and watching it import some information from the imap server, the Thrash folder seems quite long, so I went to look at it in another mailer and realized it was full of stuff I could get rid of, so I emptied the trash from Thunderbird. 

Cozy-email still works but there is an error message on the Trash folder 

```
[31mEROR[39m imap:reporter Error: fetch ended with no message
    at EventEmitter.<anonymous> (/usr/local/cozy/apps/emails/build/server/imap/connection.js:234:25)
    at EventEmitter.emit (events.js:92:17)
    at /usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1485:19
    at process._tickCallback (node.js:415:13)
Error: fetch ended with no message
    at EventEmitter.<anonymous> (/usr/local/cozy/apps/emails/build/server/imap/connection.js:234:25)
    at EventEmitter.emit (events.js:92:17)
    at /usr/local/cozy/apps/emails/node_modules/imap/lib/Connection.js:1485:19
    at process._tickCallback (node.js:415:13)
```

**Comment by arthurlutz** [comment]
Cozy is actually stuck on 19% on the Trash folder...

**Comment by arthurlutz** [comment]
Now stuck at 100% on Thrash. Couchdb is being CPU intensive and there seems to be quite a lot of IO too.

**Comment by arthurlutz** [comment]
Now whenever I do a refresh I just get "Initializing..." and no new emails since the 7th of may.

**Comment by poupotte** [comment]
This issue should be fixed now. If someone has still this issue, don't hesiste to reopen it !
