### ISSUE TITLE
Fix quick filter 

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#464]
I noticed two bugs:

* When I filter for an email or a name, it filters well but it returns emails that are 4 months old at least.
* When I empty the search field, it doesn't show my emails back.

**Comment by poupotte** [comment]
There is less problems on quick filter but some issues stay : 
* When I click on button to remove my search on recipient or sender: messages list is well diplayed but text in search is still present.
* When I remove text in this search: messages list isn't correct, it seems correspond to message send by me.

I open an issue with the two problems that I see #508
