### ISSUE TITLE
Improve extended message headers

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#47]
The layout and the information are not properly displayed. It's disappointing to see the same header as before in case of simple headers.

**Comment by clochix** [comment]
@frankrousseau could you describe what you would like to see in extended headers ?

**Comment by frankrousseau** [comment]
I put it as a reminder. I didn't think about it well. I will come back to you later about that.

**Comment by poupotte** [comment]
This issue should obsolete. @frankrousseau , Are you ok if I close it ?

**Comment by frankrousseau** [comment]
Yes  @m4dz fixed it.
