### ISSUE TITLE
A refresh button

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-emails#487]
A refresh button on each mailbox may be a great idee, I frequently use this button on other mail when I juste fill a form and I know than I will recieve a mail in few second.

**Comment by frankrousseau** [comment]
Thank you @Peltoche for reporting.

Before putting this button back we want to make it almost useless :). I mean we want to make the mail fetching automatic and efficient.

**Comment by Thatoo** [comment]
For now, on my cozy and my father's, cozy-emails are not refreshing at all. No new emails are displaying since I setup both of them. 
Cozy-emails is a little bit useless so far.

**Comment by Peltoche** [comment]
Same issue, one day my cozy-emails stop synchronising. I remove/install and it's now ok but...weird

**Comment by Thatoo** [comment]
I updated emails and it downloaded the new messages. I'll let you know if it stops working again.

**Comment by poupotte** [comment]
We can now force a refresh by opening mailbox.

**Comment by Thatoo** [comment]
it's working! That's great!
Thank you!
