### ISSUE TITLE
Conversation pane gets too large when a big set of addresses is displayed

### ISSUE THREAD

**Issue by vialibre** [cozy/cozy-emails#488]
When viewing an email with a large set of recipients, the addresses lines (To:  ,Cc:, etc.) are forced not to wrap with css "white-space:no-wrap", causing the conversation pane to overflow.

Since overflow is set to hidden, the layout is broken, with a part of the message and the buttons not visible.

**Comment by frankrousseau** [comment]
Thank you for the report @vialibre. @m4dz will look at it.

**Comment by m4dz** [comment]
Thanks a lot, we have identified this issue and already fix it in a recent commit. This will be deployed in the next release ;)
