### ISSUE TITLE
Improve contact tooltip UX

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#49]
The contact adding UX is bad: it displays poorly the contact information, the contact picture is bigger than the tooltip and the button doesn't react when mouse is over.

**Comment by frankrousseau** [comment]
I fixed it by using a default alert. I think there is no urge anymore on improving this part.

**Comment by poupotte** [comment]
In my mind, it's ok for a first improvement. I'll talk with @m4dz or @kelukelu to improve it. I'll open new issue for specific changes. Thanks @clochix .
