### ISSUE TITLE
change width of window does not keep width of left column

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#493]
Hello, on la0st email version (0.9.0), in Firefox beta (38.0.5), when only the list of message is displayed (no open message), and the page is full screen (1680*1050), if I reduce teh width of the window (stick to one side of the screen (the page is 1680/2 * 1050), the accoundt column is too small. See screen shot.
![capture_email](https://cloud.githubusercontent.com/assets/7999082/7908386/c979b0c4-0844-11e5-9100-b3b58c167dd9.PNG)

**Comment by poupotte** [comment]
We published a new version last Friday. It should fix your issues.

**Comment by poupotte** [comment]
@ZeHiro , do you still have your problem with the new version ?

**Comment by ZeHiro** [comment]
@poupotte, I couldn't test yet. I tell you when I can.

**Comment by ZeHiro** [comment]
It is good to me. Thanks @poupotte
