### ISSUE TITLE
Problem displaying a message in a conversation

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#496]
According to Abbo44, “Sur une conversation dans un message bien particulier que j'ai, j'arrive à avoir l'aperçu du contenu du dernier message reçu dans la liste des messages mais lorsque je clique sur le message particulier, alors je n'ai que l'avant-avant-avant dernier message, bref pas le dernier après je sais plus le combientième”

**Comment by poupotte** [comment]
We can't reproduce this issue. if someone has this issue, don't hesitate to reopen it and give us your logs.
