### ISSUE TITLE
Some message deletions don't work.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#497]
@frankrousseau , can you precise the scenario to reproduce this issue ?

**Comment by frankrousseau** [comment]
Not really. I sent a problematic email to @aenario. I just delete a lot of messages in a row then it happens.

**Comment by poupotte** [comment]
Your problem should be fixed with the new version. it's ok for you @frankrousseau ?

**Comment by frankrousseau** [comment]
Deletion work properly except if I delete the message from another client like thunderbird. There the message stays and I can't delete it.

**Comment by poupotte** [comment]
@frankrousseau , this issue is still available ?

**Comment by clochix** [comment]
Ping @frankrousseau

**Comment by frankrousseau** [comment]
Yes, the problem is still there.

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
