### ISSUE TITLE
RWD problems

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-emails#515]
Hello,

This time, it's not on my computer with the small resolution of 1024x600 that I have a problem. It works fine on my computer.
![capture du 2015-06-10 10 37 08](https://cloud.githubusercontent.com/assets/464782/8077256/dcb28660-0f5c-11e5-88d3-810147bc3854.png)
I can scroll to reach the button "envoyer"! If I open the side menu, it displays nicely with the inbox, sendbox, draft and stuff in a column.

It was yesterday when I tried it on a "copyright window" computer on a big screen (I forgot to check the resolution, I'll come back later to you to let you know).
It was impossible to use. I couldn't reach the "envoyer" button because I couldn't scroll with the mousse... I had to use TAB on the keyboard.
Then, I tried to open the side menu, and look at the second screenshot, it's not good, the boxes are displayed not in column but in line taking half of the screen.
Take care,
Thatoo
![index](https://cloud.githubusercontent.com/assets/464782/8077326/7f20fd32-0f5d-11e5-9b4e-d4d9169829c7.png)
![index2](https://cloud.githubusercontent.com/assets/464782/8077327/7f3530cc-0f5d-11e5-9260-e7cd925b2780.png)

**Comment by frankrousseau** [comment]
Thank you again for reporting @Thatoo!

It's a long time since we noticed the layout problem. @poupotte What do you about putting this problem at high priority level for the next sprint?

**Comment by poupotte** [comment]
Hello @Thatoo,

We published a new version last Friday, it should fixed your issues.

**Comment by Thatoo** [comment]
Right!
It's nice now.
Thank you!
