### ISSUE TITLE
No emails shown in list views

### ISSUE THREAD

**Issue by notabene** [cozy/cozy-emails#518]
Hi cozy-emails,

I connected Cozy to my email account via IMAP and everything worked fine.

But although I can see the list of IMAP folders, I can't see any email in them:

![Inbox in Cozy: empty](https://cloud.githubusercontent.com/assets/664145/8127761/899892be-10f9-11e5-9872-2fa6fe88476d.png)

Although if I look at my Thunderbird, I can see every email I have in my IMAP:

![Inbox in Thunderbird](https://cloud.githubusercontent.com/assets/664145/8127759/89921556-10f9-11e5-95f5-f087ee3cd2ba.png)

(I have checked with Roundcube and it shows the same.)

The onyl email I can see is the one I sent to @m4dz in my _Sent_ folder, and as you can see above, he has replied but his replies don't show in Cozy's inbox.

![Sent folder in Cozy](https://cloud.githubusercontent.com/assets/664145/8127760/899767c2-10f9-11e5-8abd-d910b775f7c6.png)

**Comment by poupotte** [comment]
It seems that your application applies unread filter for unknown reason. Could you try to activate/desactivate unread filter ?

**Comment by notabene** [comment]
@poupotte Yes, I tried that too, but to no avail.

**Comment by clochix** [comment]
Sorry, I reopen this one as Emails still doesn't fetch any message.
Here are some logs:
```
[32mDBUG[39m +0000 imap:reporter constructor process mailbox-refresh-deep72b2588e-eeaf-4f9d-8874-0bd0408db263
[32mDBUG[39m +0000 imap:reporter run process mailbox-refresh-deep72b2588e-eeaf-4f9d-8874-0bd0408db263
[32mDBUG[39m +0000 process:box_refresh_deep imap_refreshStep initial range: undefined:undefined
[32mDBUG[39m +0000 process:box_refresh_deep diff initial range: undefined:undefined
[32mDBUG[39m +0473 process:box_refresh_deep computeNextStep initial range: undefined:undefined next 0
[32mDBUG[39m +0000 process:box_refresh_deep nextStepEnd  range: 1:0
[34mINFO[39m +0000 process:box_refresh_deep IMAP REFRESH Trash UID 1:0
[32mDBUG[39m +0014 imap:pool 5acdd7b4781de6b523a2babd6c1e2c70 wrapped operation completed
[32mDBUG[39m +0000 process:box_refresh_deep diff#results
[31mEROR[39m +0001 processes:scheduler [Error: { error: 'query_parse_error: No rows can match your key range, reverse your start_key and end_key or set descending=true' }]
[32mDBUG[39m +0000 processes:scheduler process finished mailbox-refresh46fd7d1c-a219-452f-997d-9329c0851ae3 Error: { error: 'query_parse_error: No rows can match your key range, reverse your start_key and end_key or set descending=true' }

```

**Comment by notabene** [comment]
Hi all and thanks for your care,

BTW I migrated from DreamHost to Gandi, deleted my account from cozy-emails and recreated, and Gandi works like a breeze. Not sure it helps in the diagnostics, but who knows.

Merci et bisous anyway.

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
