### ISSUE TITLE
Settings for oauth2 gmail account

### ISSUE THREAD

**Issue by cylwin** [cozy/cozy-emails#519]
@clochix 

I'm adding the support of Google oauth for imap connection.

We have to hide some fields in the settings form :
 - hide password
 - hide advanced selection for imapserver and smtp server.
 - Add the information : Google Oauth Account 

In the new account document there is a field oauthProvider = "GMAIL".

**Comment by clochix** [comment]
@cylwin this has just been merged into the development branch, could you give it a try to check if it fits your needs ?

**Comment by clochix** [comment]
Seems ok now for @cylwin, so I put this to “Published”.
