### ISSUE TITLE
Too long recipients in messages-list

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-emails#526]
As issued in [this forum post](https://forum.cozy.io/t/app-emails/369/27), when a message has too much recipients(i.e. when someone send a mail to its whole addressbook), all recipients are displayed in the message-list cell-view, which is totally unusable. We should display recipients on one-line only to prevent the overflow.

**Comment by clochix** [comment]
59e404b is just a quick and dirty fix, I hope @m4dz will find time to propose a better, cleaner, cozier, solution.

**Comment by poupotte** [comment]
It should be nice to fix the same issue with too long title when you'll have enough time.

**Comment by poupotte** [comment]
Thanks @clochix . It works well for me :)
