### ISSUE TITLE
Contact detection don't check all contact's email addresses

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#53]
When I received a mail from a contact that has several emails recorded in the Contact application, it is not always detected. Only the first email is checked.

**Comment by poupotte** [comment]
It seems ok for me. It works for you @frankrousseau ?

**Comment by frankrousseau** [comment]
I found another bug. When you click in a name of the dropdown, nothing happens.

**Comment by poupotte** [comment]
@frankroussea, we have published a new version, it is ok for you ?

**Comment by frankrousseau** [comment]
That bug was fixed but I found two other bugs. 

* When you start typing, it shows the whole contact list. 
* Style hover of the highlighted contact make text unreadable.

**Comment by clochix** [comment]
@frankrousseau: are you sure it shows the whole contact list, and not only your contacts matching what you typed ?
It should only display the whole contact list when you click on the search icon with an empty field.

**Comment by frankrousseau** [comment]
It shouldn't display anything when you type one or two letters. It displays to many contacts. That makes things confusing.

Another style issue: the default avatar is not well centered (horizontally and vertically).

**Comment by poupotte** [comment]
Autocomplete starts after 3 characters and default avatar is, now, centered. Thus, it seems well for me. 
It is ok for you @frankrousseau ?

This improvement should be available in **version 0.6.8**

**Comment by frankrousseau** [comment]
It's ok for the next version. But now I have one bug and one suggestion:

Bug: When I enter a contact in my phone. His name is not displayed in the autocomplete menu.

Enhancement: When I add a contact it should add a removable line above. In the current situtation, when you enter more than two emails, it's almost unreadable.

**Comment by clochix** [comment]
FTR, we don't query the Contact DB when calling the atocomplete, it would take to long. All contacts are loaded on page load, so if you add a contact, you need to reload the email app to make it available.

For your enhancement request, is it related to #140 ?

I suggest we close this issue, now open for almost 2 months, and open new ones with your features requests.

**Comment by frankrousseau** [comment]
Ok. Thank you for that big feature!
