### ISSUE TITLE
Emails details deleted after saving (writing an email)

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#549]
Hello,

I tried to write an email and here is what I observed : 
- created an email
- filled adess (known adress)
- filled object
- pasted an image directly in the body of the message (no text in the message)
- the message started to auto save
- I waited the end of the aut save.
- Only the image was saved (object and To field are empty)

Important thing I guess : when I started the app, the following message is diplayed "No message for this filter" and there is no message of course.

**Comment by ZeHiro** [comment]
Problem seams to come from the "Empty filter".

**Comment by clochix** [comment]
@ZeHiro could you have a look at emails logs. If you hit an exception on client code, it should be displayed in server logs. I just got an exception when adding an attachment, I'm working on it.

**Comment by ZeHiro** [comment]
Them problem came from here https://github.com/cozy/cozy-emails/issues/550 
(at least this problem has to be first solved before reopening). The logs of the server said the mailbox wasn't found.

**Comment by clochix** [comment]
FTR, image drag and dropping was broken, see #551. This may have caused your initial problem.

**Comment by ZeHiro** [comment]
It was really copy and paste form a waebpage. And the image was inserted.
