### ISSUE TITLE
Error on update of account(@free.fr mailbox)

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#550]
Hello,
I cannot get an update from my @free.fr account . Heres is the log.

[Wed, 08 Jul 2015 07:34:23 GMT] - GET /mailbox/9ef3aea611f3a6b435e86e05bb0462ee - 200 - 109338.330 ms -  755246
EROR +30036 models:account patch conv fail { [Error: socket hang up] code: 'ECONNRESET' }
[Wed, 08 Jul 2015 07:43:00 GMT] - GET /refresh/9ef3aea611f3a6b435e86e05bb0462ee - - - - ms -  -
EROR +0023 controllers:activity { type: 'error',
  error: 
   { msg: 'TypeError: updated is undefined',
     full: 'TypeError: updated is undefined',
     stack: 'AccountStore</AccountStore.prototype.__bindHandlers/<@https://cozy.abossy.fr/apps/emails/js/app.js:12151:7\nStore</_processBinding/this.dispatchToken</<@https://cozy.abossy.fr/apps/emails/js/app.js:10329:18\nDispatcher</Dispatcher.prototype._invokeCallback@https://cozy.abossy.fr/apps/emails/js/app.js:10203:5\nDispatcher</Dispatcher.prototype.dispatch@https://cozy.abossy.fr/apps/emails/js/app.js:10173:23\nAppDispatcher</AppDispatcher.prototype.handleViewAction@https://cozy.abossy.fr/apps/emails/js/app.js:1184:5\nMessageActionCreator.refreshMailbox/<@https://cozy.abossy.fr/apps/emails/js/app.js:838:1\nmodule.exports.refreshMailbox/<@https://cozy.abossy.fr/apps/emails/js/app.js:15445:16\nRequest.prototype.callback@https://cozy.abossy.fr/apps/emails/js/vendor.js:34012:3\nRequest/<@https://cozy.abossy.fr/apps/emails/js/vendor.js:33683:5\nEmitter.prototype.emit@https://cozy.abossy.fr/apps/emails/js/vendor.js:33145:7\nRequest.prototype.end/xhr.onreadystatechange@https://cozy.abossy.fr/apps/emails/js/vendor.js:34094:5\n' },
  url: 'https://cozy.abossy.fr/apps/emails/js/app.js',
  line: 12151,
  col: 6,
  href: 'https://cozy.abossy.fr/apps/emails/#account/9ef3aea611f3a6b435e86e05bb0312a1/mailbox/9ef3aea611f3a6b435e86e05bb0462ee' }
EROR +0003 controllers:activity AccountStore</AccountStore.prototype.__bindHandlers/<@https://cozy.abossy.fr/apps/emails/js/app.js:12151:7
Store</_processBinding/this.dispatchToken</<@https://cozy.abossy.fr/apps/emails/js/app.js:10329:18
Dispatcher</Dispatcher.prototype._invokeCallback@https://cozy.abossy.fr/apps/emails/js/app.js:10203:5
Dispatcher</Dispatcher.prototype.dispatch@https://cozy.abossy.fr/apps/emails/js/app.js:10173:23
AppDispatcher</AppDispatcher.prototype.handleViewAction@https://cozy.abossy.fr/apps/emails/js/app.js:1184:5
MessageActionCreator.refreshMailbox/<@https://cozy.abossy.fr/apps/emails/js/app.js:838:1
module.exports.refreshMailbox/<@https://cozy.abossy.fr/apps/emails/js/app.js:15445:16
Request.prototype.callback@https://cozy.abossy.fr/apps/emails/js/vendor.js:34012:3
Request/<@https://cozy.abossy.fr/apps/emails/js/vendor.js:33683:5
Emitter.prototype.emit@https://cozy.abossy.fr/apps/emails/js/vendor.js:33145:7
Request.prototype.end/xhr.onreadystatechange@https://cozy.abossy.fr/apps/emails/js/vendor.js:34094:5

**Comment by clochix** [comment]
4587151 should fix the client side error handling.
The refresh fails on server side because remote server seems to close connection.
@ZeHiro does the refresh work sometime, or never ?

**Comment by ZeHiro** [comment]
Well, update works sometimes. But usually it is not really working.

**Comment by clochix** [comment]
@aenario delegating this one to you (you know, I like to delegate :-P )

@ZeHiro could you describe what do you mean by “not really working” ?

**Comment by ZeHiro** [comment]
I need to test the fix first (build the client). 
And by 'not really working' is "I roll the dice and I can see mails or not" usually the mails are not complitly up to date.

**Comment by clochix** [comment]
@ZeHiro please wait, I didn't even create a PR with this fix ;-)

**Comment by ZeHiro** [comment]
I did the fix on my own :)
