### ISSUE TITLE
Display bug when entering long email addresses

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#554]
See https://forum.cozy.io/t/emails-bugs-et-incomprehension/923

**Comment by poupotte** [comment]
It works well for addresses at the beginning of line. However, it's still problematic for addresses at the end of input. Indeed, if an address is too long, it skips a line and hides beginning of address.

**Comment by clochix** [comment]
@poupotte I did a little fix for addresses et the end of input, could you give it a try ? Thanks !

**Comment by poupotte** [comment]
It works well. Thanks @clochix :)
