### ISSUE TITLE
Problem to add wanadoo account

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#560]
From [forum](https://forum.cozy.io/t/emails-impossible-de-se-connecter-avec-ces-parametres/845)

**Comment by clochix** [comment]
I finally [found the solution](https://forum.cozy.io/t/resolu-emails-impossible-de-se-connecter-avec-ces-parametres/845/7) : the default SMTP server only works on Orange IPs, on other servers we have to use the following parameters:
- serveur : smtpauth.orange.fr
- port : 587
- SSL : no
- STARTTLS : yes

**Comment by poupotte** [comment]
Thanks @clochix . It works well o/ (see [forum](https://forum.cozy.io/t/resolu-emails-impossible-de-se-connecter-avec-ces-parametres/845/6))
