### ISSUE TITLE
Simplify add/show contact ux in message headers 

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#568]
Currently add/show contact UX is messy. 

I fixed it in this PR by making things less sexy but more efficient and simpler. See this PR: https://github.com/cozy/cozy-emails/pull/565

I face problems with tooltips. Everything looks well configured but the tooltips doesn't show on buttons.

**Comment by poupotte** [comment]
It works for me/ Thanks @frankrousseau
