### ISSUE TITLE
Email account password deleted (or lost)

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#569]
HEllo,

I noticed I didn't receive mails anymore. It appeared I had to reneter my email to have it sync again. Is it possible the password ws lost for the same reason as in konnectors?

**Comment by clochix** [comment]
Hello @ZeHiro,
Thanks for reporting. Emails has nothing to do with Konnectors, and I don't think this is the same problem. Have you kept the server logs ?

**Comment by ZeHiro** [comment]
I cans send you logs (concerning other problems) But I still have lots of problems with emails (I guess 8000 mails on a RPI2 is a bit mutch).

**Comment by clochix** [comment]
Yes please, send us the Mail app logs to support at cozycloud.cc (if you restarted the app since hitting this problem, you could also send us the `emails.log-backup` file). Thanks !

**Comment by ZeHiro** [comment]
I'll send you the logs i have. Then i'll make a full reinstall of emails (including deletion of all emails related info from db, i think i have a completly messed up index, and given the computing power of my server i think it is better this way)

**Comment by poupotte** [comment]
This issue should be fixed with new data-system.
