### ISSUE TITLE
When clicking on "Open application" the opened account should be the one for the notification

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#570]
Hi,
I have several accounts in emails. When clicking on the "Open application" button in the notification, I expect the appropriate account to be opened, and not the default one. 
Thanks

**Comment by clochix** [comment]
Thanks for reporting, we'll fix this soon :-)

**Comment by clochix** [comment]
Hi @ZeHiro,
This should be in the latest version of the application, could you give it a try ?

**Comment by ZeHiro** [comment]
@clochix it works. Thanks
