### ISSUE TITLE
Strange behaviour of SSL checkboxes

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#573]
STR:
 - change IMAP or SMTP server port to a value without SSL (143 for IMAP ou 25 for SMTP);
 - the SSL box is unchecked;
 - validate the form;

Expected: nothing change;
Actual: SSL box is checked again;

Side effect: a user [tried to connect](https://forum.cozy.io/t/solved-can-not-add-an-email-account-in-emails-app/1020) to SMTP server on port 25, so without SSL, but we tried to connect to port 25 with SSL, so the connection was refused.

**Comment by encolpe** [comment]
Another strange behavior related to this one with 0.9.21:

- for the smtp server, if you check the ssl box, both boxes are checked then if you unckeck only one the port goes on 25.
- if only one box is checked and you check the second one the port value goes on the value of the last checked.

The relative code [client/app/components/account_config_main.coffee#L69](https://github.com/cozy/cozy-emails/blob/master/client/app/components/account_config_main.coffee#L69).

**Comment by clochix** [comment]
Thanks for reporting @encolpe. We'll have a look at this. This code is pretty complex, we try guess the port based on user choices, also allowing the user to set the port.

**Comment by greinbold** [comment]
However, actually is not possible to set the SMTP server to STARTTLS with port 25... Can we fix this ?

**Comment by clochix** [comment]
Hi @greinbold,
This screen has been fully rewritten during [current refactoring of the application](https://forum.cozy.io/t/maintenance-of-email-application/2320). Pinging @m4dz to ensure this issue has been fixed in the new version.

**Comment by m4dz** [comment]
Yep, I can confirm this is fixed in our last development version :smile:

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
