### ISSUE TITLE
Special Folders form is broken

### ISSUE THREAD

**Issue by Morreski** [cozy/cozy-emails#578]
The wrong field is modified when i want to change my mail special folders.

**How to reproduce the bug:**
When a mailbox is created. Edit your Trash Folder. (e.g a folder named "A")
Then, change your Draft folder (Folder named "B")

**What was expected:**
My trash folder is "A"
My Draft folder is "B"

**What happens instead":**
My trash folder is "B"
My draft folder is not modified

**Comment by clochix** [comment]
Thanks for reporting @Morreski, I think I just found the bug, the fix will be available very soon ☺

**Comment by clochix** [comment]
Hi @Morreski,
This should be fixed in latest version of the application. Could you give it a try ? Thanks!

**Comment by Morreski** [comment]
Hi @clochix,

It works perfectly fine now.
Thanks.

**Comment by clochix** [comment]
Thanks for testing @Morreski, closing this :-)
