### ISSUE TITLE
Re-index after account import

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#581]
Hi,
I mported an account, and I got a timout (504) when trying to open the emails app again. After stopping and starting the app again (and so after reindexing), everything went fine. Then, shouldn the indexer launched at the enf of import (or long sync)?

**Comment by aenario** [comment]
Hi @ZeHiro , good idea, I am working on the overhaul of the import / refresh process and i will add a reindexing during import.

**Comment by poupotte** [comment]
@ZeHiro, this issue should be fixed now. I close this issue but if someone has this issue, don't hesitate to reopen it ;) !
