### ISSUE TITLE
Deleting with the trash button seems broken

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#587]
As reported by some users, for example [here](https://forum.cozy.io/t/cozy-emails-trash-button-doesnt-do-anything/1115/3).

**Comment by clochix** [comment]
Browsing into logs, I found an error on lines [297-298](https://github.com/cozy/cozy-emails/blob/master/client/app/components/message.coffee#L297) of `message.coffee`. This is probably related.

**Comment by aenario** [comment]
This should have been fixed.

**Comment by poupotte** [comment]
It's ok for me. Thanks @aenario
