### ISSUE TITLE
Reindexation window won't go away

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-emails#589]
I upgraded the Email application to 0.9.7 and since then I get a window:
https://nicolas-6.cozycloud.cc/public/files/files/528aea955ccf1fdedc73e2b7ca670410/attach/email-reindex.png

Cozy instance hosted on cozy cloud infratsructure (nicolas-6)
Data System: 2.0.6
Proxy: 2.1.0
Home: 2.0.7
Controller: 2.0.30
Emails -  0.9.7

And this window is actually being put in front of other applications (Etats, Contacts, Photos...). When I open an application, it open correctly but after a few seconds, the "reindex" window comes on top.

**Comment by clochix** [comment]
Thanks @nicodel, and sorry, I forgot your ticket and opened a new one this morning, #590. Both should be resolved quickly.

**Comment by aenario** [comment]
This should have been fixed in just released 0.9.8 version
