### ISSUE TITLE
Bad number unread messages

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-emails#592]
Salut!

J'ai actuellement tout mes messages notés comme lu mais le menu de gauche m'annonce encore des non ouvert. Si je tente de d'afficher que les messages non lue j'en ai aucuns.
Cela fait un moment que j'ai ce probleme donc je ne peux pas vraiment vous dire depuis quelle version cela vient mais dans dans la derniere (0.9.8) le probleme existe toujours.

Le probleme peut venir de la synchronisation avec mon client mail sur mon telephone (K9mail) que j'utilise tres souvent. Cela semble une erreur qui arrive de temps en temps de facon plus ou moins aléatoire, je n'ai pas réussit a le reproduire de facon fixe.
L'autre probleme est que vue que j'utilie mail depuis un moment les écarts s'amplifient: je suis a 40 messages marqué comme non lu dans le menu donc si il y avait un moyen de remettre les compteurs a zero litteralement.

**Comment by clochix** [comment]
Merci pour ce rapport @Peltoche.
Est-ce que tu as ce nombre de messages non lus correspond à l'ensemble du compte, ou à la boite de réception ? Est-ce que tu n'aurais pas des messages non lus dans d'autres dossiers, comme le dossier Envoyés ?

**Comment by Peltoche** [comment]
J'ai plusieurs boites de reception, dans chacune j'ai un ecart plus ou moins grande. Je n'utilise pas les dossiers j'ai donc aucuns mails dedans. Par contre je viens de voire que sur mon compte XXX j'ai il me marque 13 mails non lus: 12 a tord plus un mais effectivement nouveau. Si de deplois ma boites ("All")  il me marque 17 mails non lus: 16 a tord plus un reel. Quand j'ai ouvert mon nouveau message les deux compteurs se sont bien décrémenté passant a 12 dans "la categorie" Inbox et 16 dans "le dossier" Inbox.

**Comment by Peltoche** [comment]
Une idée m'est venue: recevant pas mal de mail, il se peut qu'il y ai effectivement un mail non lu mais qu'il soit descendu dans les fin fond et qu'il n'apparaisse pas dans les premiers mails affichés. J'ai donc scroller un peu (3/4 chargements de messages), tout séléctionné et marquer comme non lu mais cela n'a pas marché. Il est possible que les messages soient encore plus bas mais je pense que j'aurais du au moins en croiser un. J'ai ouvert plusieurs discussions pour m'assurer qu'il n'y avait pas un message non lu dedans mais pareil, aucuns effets.

Petite questions:
 
Quand j'utilise le bouton "unread", il m'affiche les messages non lus parmis ceux chargé sur le client ou il fait la recherche coté serveur sur tout les mails de la boite y compris ceux non chargé?

Ces variables qui gerent le nombre de messages non lues, elles sont recalculées a chaque chargement de page ou ce sont des variables en BDD qui sont simplement incrémentées/decrementées?

**Comment by nicodel** [comment]
Bonjour,

J'ajoute ma petite pierre. Je ne peux pas avoir 3464 courriels non dans cette boite...
![emails-nb-unread](https://cloud.githubusercontent.com/assets/1799460/9197727/22899376-4037-11e5-8036-60f02febf6e6.png)

Les logs d'Emails peuvent être consultées [içi](https://nicolas-6.cozycloud.cc/public/haste/GzwErhNd).

**Comment by clochix** [comment]
@Peltoche le filtre « non lus » fait une requête au serveur et affiche tous les messages non lus dans la boite. L'utiliser devrait donc t'afficher ces fameux douze messages non lus.

**Comment by EtienneM** [comment]
Je ne sais pas si ça aidera mais j'ai le même souci et, avec Firefox, je viens de faire CTRL+Shift+R pour recharger la page et ça a remis le compteur à une bonne valeur.

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
