### ISSUE TITLE
Error creating folder

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-emails#594]
Salut,

Le message d'erreur:
```
Error creating folder Argh, I'm unable to perform this action, please try again
```

La procedure:

- Creer un nouveau dossier dans choisir de parents
- Creer un autre dossier avec en parents le dossier precedent.

**Comment by poupotte** [comment]
This issue should be now fixed. @peltoche, is it fixed for you ?

**Comment by poupotte** [comment]
@aenario, this issue seems still available. Could you check it ?

**Comment by clochix** [comment]
Hi @Peltoche,
This should be fixed for some time now, is it ok for you?

**Comment by Peltoche** [comment]
Yes, all good! Thanks!
