### ISSUE TITLE
Updating name folder

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-emails#595]
Yop,

message:
```
Error updating folder Argh, I'm unable to perform this action, please try again
```

Procedure:
Il suffit d'essayer d'update une des deux boites INBOX.

Les boites DRAFT / SEND / TRASH elles par contre s'updatent sans problemes

version de mail : 0.9.8

**Comment by clochix** [comment]
Hello @Peltoche,
En fait, je pense surtout qu'il faudrait interdire de mettre à jour le nom de la boite de réception et des dossiers spéciaux. Si tu les renommes, le serveur risque fort d'être perdu, et tu t'exposes à des soucis aléatoires.
@aenario, @poupotte  qu'en pensez-vous ?

**Comment by poupotte** [comment]
Oui, je suis d'accord avec @clochix , le renommage des dossiers spéciaux pose pas mal de soucis. Nous avons d'ailleurs une issue ouverte à ce sujet https://github.com/cozy/cozy-emails/issues/290.

**Comment by poupotte** [comment]
Je ferme ce ticket. Pour suivre le blocage du renommage des dossiers spéciaux, vous pouvez suivre le ticket #290.
