### ISSUE TITLE
Number of unread messages is not properly displayed

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#60]

**Comment by jsilvestre** [comment]
I +1 this issue, that's something import for me as a user.

**Comment by poupotte** [comment]
Number of unread messages for account doesn't seem work. I haven't unread mail in my mailbox and application displays 125 unread messages :/ . @aenario , don't hesitate if you want more information.

**Comment by poupotte** [comment]
it works for me. Thanks @aenario  (it takes long time between update and correct counter)
