### ISSUE TITLE
On folder page: enter delete mailbox

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-emails#601]
Salut,

J'ai voulue update le nom d'une boite et naturellement j'ai appuyer sur entrer et au lieux de confirmer mon update cela m'a proposer de supprimer la boite mail. Allant vite, forcement j'ai appuyer sur entre une nouvelle fois... Tout ca pour dire que la boite me semble un peu trop vite supprimable, une demande d'ecrire le nom de la boite (comme github) pourrait sembler interressant. En tout cas ne pas binder la suppression avec la touche entre.

Bonne chance :smile:

**Comment by poupotte** [comment]
Bonjour @Peltoche,

merci pour ce retour :)
Je ne suis pas sûre d'avoir bien compris : vous allez sur la page de paramètre de votre compte mail. Puis vous modifiez le champs 'Account Label' et cliquez sur 'Entrer'. C'est à ce moment qu'on vous propose de supprimer votre compte au lieu de le mettre à jour ?
En testant ce scénario sur mon cozy, l'application me met bien à jour mon compte (sans m'afficher la pop-up de suppression du compte).

**Comment by poupotte** [comment]
Je viens de le reproduire en renommant un dossier de mon compte mail (et non mon compte). J'avais mal compris, merci @Peltoche pour ce retour :)

**Comment by poupotte** [comment]
Ce problème devrait être résolu avec la nouvelle version d'emails. @peltoche, avez-vous encore ce soucis ?

**Comment by poupotte** [comment]
@aenario, ce problème ne semble pas être résolu avec mon Cozy en production. Peux-tu y jeter un oeil ? (version 0.9.12)

**Comment by clochix** [comment]
Bonjour @Peltoche,
Ce ticket est-il toujours d'actualité ?

**Comment by Peltoche** [comment]
Yep, c'est bon. Merci a vous !
