### ISSUE TITLE
Upgrading from 0.9.10 to 0.9.11 fails

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-emails#613]
Data System: 2.0.7
Proxy: 2.1.1
Home: 2.0.10
Controller: 2.0.31
Emails - 0.9.10

Steps to reproduce:
1. Have Emails up and running on version 0.9.10.
2. Launch the upgrade through the "Etats" application

What happens:
Upgrade fails, showing "Application cassée".

What should happen:
Well, application is upgraded to the new version.

[Here](https://nicolas-6.cozycloud.cc/public/haste/JccRftJ) are the logs that appear when the application is "cassée".

**Comment by frankrousseau** [comment]
I just pushed a fix without version it. Could you try to uninstall / reinstall your app and tell me if it's working.

**Comment by nicodel** [comment]
It works! Emails is up and running. Thank you.

**Comment by frankrousseau** [comment]
Great!
