### ISSUE TITLE
Update of view when emptying trash

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-emails#615]
When emptying the trash of an account (with the recycle icon). Here are the problem I observed : 
- I get a comment that the trash was emptied, but the mails are still visible. When clicking on the trash folder again, the render is updated.
- The number of messages in the trash bin (when the mouse is over the folder in the right column is not updated. On the below screenshot, the mous is over the "Trash folder"

![email](https://cloud.githubusercontent.com/assets/7999082/9601520/72f8af7e-50a2-11e5-8d36-38a30517341d.png)

**Comment by ZeHiro** [comment]
In fact, the problem is more global, the displayed number or unread messages is not updated on update of a box/filter

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
