### ISSUE TITLE
Error "flag Ko"

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-emails#617]
Salut,

j'ai un paquet de notification: "flag Ko" et des erreurs sur la suppression qui arrivent de facon plus ou moins aleatoire. J'ai trouver un peu de log qui pourait etre utile:

```
DBUG +0000 imap:pool { user: 'peltier@halium.fr',
  password: '****',
  host: 'ssl0.ovh.net',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false } }
DBUG +4995 imap:pool 59a05e92f605fc63e28f9cd91004684b connection error on ssl0.ovh.net:993
DBUG +0000 imap:pool RAW ERROR { [Error: Authentication failed.] textCode: 'AUTHENTICATIONFAILED', source: 'authentication' }
DBUG +0000 imap:pool 59a05e92f605fc63e28f9cd91004684b giveup { name: 'AccountConfigError',
  field: 'auth',
  message: 'on field \'auth\'',
  stack: '',
  original: { [Error: Authentication failed.] textCode: 'AUTHENTICATIONFAILED', source: 'authentication' } }
```
```
DBUG +0000 imap:pool { user: 'peltoche@halium.fr',
  password: '****',
  host: 'ssl0.ovh.net',
  port: 993,
  tls: true,
  tlsOptions: { rejectUnauthorized: false } }
DBUG +5153 imap:pool 59a05e92f605fc63e28f9cd9100009ae connection error on ssl0.ovh.net:993
DBUG +0000 imap:pool RAW ERROR { [Error: Timed out while authenticating with server] source: 'timeout-auth' }
DBUG +0000 imap:pool 59a05e92f605fc63e28f9cd9100009ae giveup { name: 'AccountConfigError',
  field: 'imapTLS',
  message: 'on field \'imapTLS\'',
  stack: '',
  original: { [Error: Timed out while authenticating with server] source: 'timeout-auth' } }
```
j'ai pas mal d'autre petites variante mais l'idée est la: j'ai un probleme d'authentification ou de time out

**Comment by clochix** [comment]
Thanks for reporting @Peltoche.
When do you see the “Flag KO” errors ? Only when deleting messages, or every time you update a flag (for example, when marking a new mail as read).

Also, this seems to be connection problem between your server and the IMAP server of your provider. Could you perform some low level checks to ensure there aren't random connection problem between the two servers ?

**Comment by Peltoche** [comment]
I think is every time. I can make the checks, ping me on IRC: I have the same login

**Comment by clochix** [comment]
Here's a script you can use to test the connection to IMAP server. It uses the `expect` utility, you'll probably need to install it on your server. The script returns 0 if everything worked fine and 1 otherwise. Maybe you can use this script with a monitoring tool to periodically check the connection.

```
#!/usr/bin/expect  --
set host ssl0.ovh.net
set port 993
set user youruser
set pass yourpassword

set timeout 30

spawn openssl s_client -crlf -connect $host:$port -crlf

expect "Welcome to OVH Mail server" { send "a login $user $pass\r" }
expect "OK" { send "a list \"\" \"*\"\r" }
expect "OK" { send "a logout\r" }
expect "OK" { exit 0 }

# On error or timeout return 1
exit 1
```

**Comment by nikksno** [comment]
Hi there!
I ran the script. After all of the connection details it returnes:
```
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready!!
a list "" "*"
a BAD Error in IMAP command received by server.
```
How can I fix this on the server side?
Thanks for your time

**Comment by clochix** [comment]
Hi @nikksno,
There's probably no error on your IMAP server. This script is very basic, crafted to work with the IMAP server of OVH.
The settings of your Dovecot server are different, and the script fails, but it doesn't mean the server don't work. If you want to use this script to monitor your connection, you need to adapt the IMAP commands sent to the server.

**Comment by nikksno** [comment]
Very good thank you very much @clochix. I'll look into this.

**Comment by poupotte** [comment]
@Peltoche this issue is still relevant ?

**Comment by Peltoche** [comment]
No, it's OK for me

**Comment by frankrousseau** [comment]
Ok thank you all for your participation.
