### ISSUE TITLE
Handle IMAP servers with STARTTLS and LOGINDISABLED

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#625]
See [this thread](https://forum.cozy.io/t/emailaccount-with-strong-crypto-does-not-work/1270).
An IMAP option is missing to connect to servers configured with STARTTLS and LOGINDISABLED.

**Comment by clochix** [comment]
This fix works for the user, but it would be great to check that it doesn't break connection to other servers.

@aenario, do you know if we can play with this options in our Dovecot test server ?

**Comment by infoomatic** [comment]
using dovecot 2.2.18-current, the relevant config is:
ssl = required
ssl_protocols = !SSLv2 !SSLv3
ssl_cipher_list = EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA
ssl_prefer_server_ciphers = yes
ssl_dh_parameters_length = 4096

**Comment by poupotte** [comment]
Thanks @clochix :) .
