### ISSUE TITLE
Improve attachments icon visibility

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-emails#627]
It should be nice to improve attachment visibility, espacially on conversation.

**Comment by kelukelu** [comment]
To improve the visibility in a conversation, I suggest to show the attachment icon event when the conversation are collapsed.
<img width="651" alt="screen shot 2015-09-15 at 10 58 59" src="https://cloud.githubusercontent.com/assets/7029620/9872755/b711b2a6-5b9b-11e5-87de-324679e36583.png">
If it is not visible enough, adding a lightgrey background color can be a good idea
