### ISSUE TITLE
There's no way to delete an attachment from a draft message

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#66]
The delete icon is explicitly hidden, so I suppose there's a reason…

**Comment by clochix** [comment]
@frankrousseau any news on this ? I can't reproduce. could you open the JS console and see if you get an error ?

**Comment by frankrousseau** [comment]
Looks good. If found another bug. I will open an issue about it later (when you refresh the app when a draft is displayed you lose the body of the draft).

Thank you!
