### ISSUE TITLE
Problem modifying an account immediately after its creation

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#67]
Quote from an early tester:

    tiens j'ai voulu revenir sur "modifier le compte " pour changer le nom du compte : impossible
    à chaque fois que je veux changer une lettre dans le champ "nom" le nom initial se remet automatiquement
    le champ est impossible à effacer avec la touche retour arrière

Problem disappear after reloading page

**Comment by frankrousseau** [comment]
Looks good.
