### ISSUE TITLE
Action button disabled when opening an email

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#673]
Source : https://forum.cozy.io/t/email-version-0-9-15/1514

> lorsque je lis un mail, les boutons réponse, transfert,, suppression, etc.. sont grisés et inaccessibles. Je ne peux qu'accéder au menu déroulant qui permet de marque la conversation comme non lu.

> C'est très génant vu que ça empêche de répondre aux mails.

The bug auto fixed itself after sometime.

**Comment by poupotte** [comment]
We can't reproduce it, I close this issue. If someone has this error, don't hesitate to reopen it.
