### ISSUE TITLE
[feature request] A delete feature for messages without being obliged to open-read them

### ISSUE THREAD

**Issue by goofy-bz** [cozy/cozy-emails#68]
It happens every now and then that a quick glance on a mail title is enough to decide to delete it. In the current config, you need to open the message and display it in the side column to be able to find the tiny trashcan button.
I wish I could delete one message at once with a little delete icon next to its title or with a big delete button displayed permanently and active as soon as one message title is focussed.
Also, a confirm deletion message is careful and ok but there should be the option to skip confirmation dialog in the settings of the account.
Please help me to kill all these fucking useless messages efficiently :)

**Comment by clochix** [comment]
There's a big need of better document settings. This one may be related to #152 

Do you have any idea on how to improve discoverability of this features ?

**Comment by poupotte** [comment]
I close this issue, missing documentation is in issue #152.
