### ISSUE TITLE
Invalid tree view

### ISSUE THREAD

**Issue by EtienneM** [cozy/cozy-emails#694]
Salut,

Je viens d'essayer cette application et j'ai un petit souci. La vue arborescente est complètement fausse. Le décalage vers la droite des sous-répertoire n'est pas toujours bon et l'ordre de haut en bas des répertoire et sous-répertoire n'est pas non plus correct. Je n'ai pas vu de bug à ce sujet mais peut être est-ce à cause de mon arborescence ?

J'héberge mon Cozy  la maison sur un Raspberry Pi et tout est à jour.

**Comment by nono** [comment]
Salut,

j'ai le même problème. Je crois que c'est parce que les répertoires sont triés par ordre alphabétique sans tenir compte de l'arborescence.

**Comment by clochix** [comment]
Bonjour @EtienneM,

Merci de ce signalement. Est-ce que tu pourrais nous dire quel prestataire héberge tes messages ? Certains serveurs IMAP ont des configurations un peu exotiques que nous ne gérons peut-être pas.

**Comment by EtienneM** [comment]
Il s'agit de l'université de Strasbourg. Je pense qu'ils utilisent SOGo si ça existe.

**Comment by nono** [comment]
@clochix je ne pense pas que ce soit ça. Ça me le fait pour l'email cozycloud : 

![cozy](https://cloud.githubusercontent.com/assets/2767/11680086/2b660d44-9e56-11e5-82a3-61935d4b5926.png)

Et dans thunderbird : 

![thunderbird](https://cloud.githubusercontent.com/assets/2767/11680087/2b8d3d56-9e56-11e5-867b-b070943d2964.png)

**Comment by EtienneM** [comment]
Pour info, j'ai supprimé puis ré-installé l'application et je n'obtiens pas le même ordre. Le nouvel ordre est un peu mieux même si toujours pas complètement correct.

**Comment by poupotte** [comment]
Bonjour @EtienneM , nous travaillons sur une nouvelle version de l'application emails. Ce ticket n'est plus valable sur cette nouvelle version.
