### ISSUE TITLE
realtime trigger as many events as tabs opened in browser

### ISSUE THREAD

**Issue by misstick** [cozy/cozy-emails#749]
- I open Email in 3 different tabs in my browser (Chrome),
 - I create a new message and save It into draft : one single action `MESSAGE_SEND ` is sent,
 - `RECEIVE_RAW_MESSAGE_REALTIME ` is triggered 3 times,
 - the same message is diplayed 3 times into draft message list (same `messageID` && `conversationID`).

Only 1 message should be visible int that list.

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
