### ISSUE TITLE
Conversation: every messages are loaded in the left column

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-emails#76]
When a conversation is displayed, every messages are loaded in the left column. 
An easy way to reproduce it is to make one email of the conversation as important. Then reload the app. Apply the important filter, then click on the conversation message. You should see the weird message list in the left column.

**Comment by poupotte** [comment]
With new conversation management, I can't reproduce this issue.  @frankrousseau , it is ok for you ?

**Comment by frankrousseau** [comment]
Same as you.
