### ISSUE TITLE
When editing a draft, message view is sometimes editable or readable

### ISSUE THREAD

**Issue by misstick** [cozy/cozy-emails#764]
1. I click on a draft in the list : it appear on edition mode in a 2nd panel
2. I press 'bottom' on my keyboard
- focus is on previous message (OK)
- the message in 2nd panel is on read only

Whatever the way to access to a draft message in the list, it should display a message on edition

**Comment by poupotte** [comment]
This issue is not relevant anymore because we're working on a new Emails version.
