### ISSUE TITLE
When editing a save draft, we don't get the HTML editor

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#79]

**Comment by frankrousseau** [comment]
It looks to work but it doesn't display the previous email when the user clicks on the '...' button.

**Comment by poupotte** [comment]
It seems good. Thanks @clochix. It is ok for you @frankrousseau ?

It should be available in **version 0.6.8**

**Comment by frankrousseau** [comment]
That's ok. Thank you!
