### ISSUE TITLE
Error message should disappear when changing mailbox

### ISSUE THREAD

**Issue by goofy-bz** [cozy/cozy-emails#80]
I experienced this
1. Tried to delete one message in the Trash box
2. Got this ominous pink-backgrounded poem  "Argh, I'm unable to perform this action, please try again" (I like poetry no prob)
3. Clicked on another mailbox (hence leaving the Trash box)
4. When content of the *other* mailbox is displayed, there is still the persistent error message which is now a meaningless visual annoyance.

Only mean to make it disappear is to click on the cross on top right corner. 
I suggest it should disappear by itself when user changes its focussed mailbox.

**Comment by poupotte** [comment]
It seems work. @goofy-bz, it's ok for you ?

**Comment by goofy-bz** [comment]
Yes the message is now self-removing. Good job done, thx.
