### ISSUE TITLE
Cozy Emails created empty new folders inside my INBOX.

### ISSUE THREAD

**Issue by terrycloth** [cozy/cozy-emails#805]
I logged into Cozy Emails to read some mail. I did nothing but open the app and read messages. For some reason, Cozy Emails created new subfolders under my INBOX folder.

I use Cozy (a beta account on cozycloud.cc) for an email account set up by my web host to go with my domain and web hosting service. My webhost set up the email account so that all folders are subdirectories under INBOX. So it normally looks like this.

* INBOX
    * Archive
    * Drafts
    * Sent
    * Trash

Cozy created an extra "INBOX" folder, containing a "Trash" folder, so now it looks like this.

* INBOX
    * Archive
    * Drafts
    * INBOX
        * Trash
    * Sent
    * Trash

**Comment by clochix** [comment]
Hi @terrycloth,

Did you change something?
I'm unable to reproduce your issue. Your box tree doesn't seem to contain an Inbox folder inside Inbox, neither in Cozy database nor when fetching your IMAP server.

**Comment by terrycloth** [comment]
I deleted the extra folders when I noticed them. :/

**Comment by clochix** [comment]
Thanks @terrycloth,

@aenario: I didn't see anything in the logs (but the creation of this wrong folders may be older than our logs). Do you want that I backup them somewhere so you could have a look later?

**Comment by terrycloth** [comment]
I apologize, I now believe this problem may have been created by a different mobile email client. Most of the time I use my desktop email client, so I guess I mixed up which was the problem.

In my attempts to reliably reproduce the issue, I've ruled out Cozy Emails, though.

Again, sorry, and thanks.
