### ISSUE TITLE
No helpful message when a new mail account creation fails

### ISSUE THREAD

**Issue by goofy-bz** [cozy/cozy-emails#82]
Here is what I recently experienced:
1. Clicked on the left-hand side button in order to create a new mailbox account.
2. Filled the various fields and probably dropped wrong parameters :)
3. Instead of one expected error message such as:
*Connection failed, please check your parameters or contact you sysadmin*

...there appeared a long yellow streak without information nor comfort :) **see screenshot**
![erreurcreationcompte](https://cloud.githubusercontent.com/assets/858630/5424767/f602fbbc-82fe-11e4-9cf0-2781cc96279b.png)

**Comment by clochix** [comment]
I think it has been fixed a while ago. Could you give it another try and report here any case when you still encounter the problem ?
Thanks !

**Comment by goofy-bz** [comment]
Yessir there is now a nice friendly message telling me "Serveur d'envoi invalide" twice:
* in a yellow upper streak  
* in a message below the appropriate failing field  
thank you, dear witchdoctor of code.
trivial:  in French there is "Serveur d'envoi" (2x) and "Serveur sortant", though it is rather clear I think this can be unified somewhat.
