### ISSUE TITLE
Add an info about the refactoring

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-emails#835]
I see a lot of users complaining about the Emails app, either about the instability (that's currently being dealt with with a giant refactoring), or the disabling of basic features such as messages composition (for the said refactoring). It would be nice to have a little text information within the client to inform the user that the app is currently being completely remade instead of making them wonder if something went wrong [and try to debug it](https://forum.cozy.io/t/email-no-compose-functionality/2420/2).

**Comment by clochix** [comment]
That was a nice idea @babolivier, but I think we won't publish a new version before the Big New One, so unfortunately I don't think we'll implement this. I close this issue, if you have any objection, feel free to reopen it.
