### ISSUE TITLE
Allow to use a login distinct from the address

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#84]
Add a login field to IMAP and SMTP parameters

**Comment by clochix** [comment]
I added Advanced SMTP parameters, that allow:
 - to select authentication method. It's useful when using a local SMTP server that don't require auth;
 - to use another login / password for SMTP server.

Dou you think I should do the same for IMAP ? Imho, the main login / password of the account should be enough to connect to IMAP server.

(the code will be on next merge)

**Comment by frankrousseau** [comment]
I think we should do it when an user will ask it. We should not add too much features too early.

**Comment by clochix** [comment]
@poupotte STMP advanced parameters have been added some times ago, and we won't add IMAP advanced parameters for now, so could we close this one ?

**Comment by clochix** [comment]
I re-open this as one user rised this issue yesterday.
