### ISSUE TITLE
Improve mass deletion

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#89]
STR:
 - create a bunch of draft messages;
 - in draft folder, select them all and click the trash icon;
 - deletion is slow (less than 1s for the firsts messages, around 2.5s after) and the browser has trouble displaying all confirmation dialog;

**Comment by poupotte** [comment]
It's ok for client side (only one confirmation dialog and faster deletion). I add an other issue (https://github.com/cozy/cozy-emails/issues/132) to refactoring mass deletion with server-side.
