### ISSUE TITLE
User should'nt be able to create or delete message when special mailboxes are undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#92]

**Comment by frankrousseau** [comment]
What do you mean by special mailboxes?

**Comment by clochix** [comment]
Special mailboxes are "Draft", "Sent" and "Trash". If the user try to display message list without having a trash folder, he will be redirected to account config (because without Trash, deletion won't work).

**Comment by poupotte** [comment]
I can't test because I already configured my draft and I can't undefined it.

**Comment by clochix** [comment]
You can test by manually updating the account in CouchDB.
But the client will now do its best to detect “special” folders, so it may be difficult to unset them.

**Comment by poupotte** [comment]
Thanks @clochix, it works well.
