### ISSUE TITLE
Allow to empty trash

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-emails#93]

**Comment by clochix** [comment]
@aenario is there already some server-side code to do this ?
@frankrousseau any suggestion about the UI ? An icon inside the menu ? A button in account config ?

**Comment by poupotte** [comment]
It works well but I think it lacks of user information. Indeed, I click on icon to empty my trash, then I confirm and nothing. After about 30 seconds my mails are well removed. A spinner or an other indication to inform user would be nice.

**Comment by clochix** [comment]
Expunging may take a long time server side, so I now assume everything works and remove all messages from display immediately. If expunge fails, the list will be refreshed.

**Comment by poupotte** [comment]
Nice, it's good for me. Thanks @clochix .

It will be available in **version 0.6.8**
