### ISSUE TITLE
"Message saved" notifications don't disappear

### ISSUE THREAD

**Issue by gabeos** [cozy/cozy-emails#95]
When composing a message, the blue "Message saved" notifications pile up and wait for manual dismissal. I also currently have four that are unresponsive to clicks, and won't go away at all. 

I appreciate the notification, but it should disappear on it's own, or, better, remove the notification and embed the functionality in the "Save Draft" button, greying it out when it's auto-saved or some other subtle visual notification.
![cozy-save-message](https://cloud.githubusercontent.com/assets/751112/5481347/c20cd59a-8604-11e4-998d-24bfb84177b3.png)
![cozy-redacted](https://cloud.githubusercontent.com/assets/751112/5481461/6e2a7d04-8606-11e4-8888-64c283243f86.png)

**Comment by poupotte** [comment]
It works for me. @gabeos, it ok for you ?

**Comment by gabeos** [comment]
yup, works for me now as well. thanks!
