### ISSUE TITLE
Add Notifications

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-emails#96]
Cozy & Desktop

ref. https://developer.mozilla.org/en/docs/Web/API/notification

**Comment by frankrousseau** [comment]
How can I test? I mean when notification occurs. I checked the notifications in the settings screen. But I don't know when it should be displayed.

**Comment by aenario** [comment]
Notifications are based on the \\Recent flags, so this feature is not actually working until https://github.com/cozy/cozy-emails/issues/109 is handled.

**Comment by frankrousseau** [comment]
ok

**Comment by poupotte** [comment]
It works for me. Thanks @aenario .
